### ISSUE TITLE
[Bug] Framerate drop bug?

### ISSUE THREAD

**Issue by freethemice** [xenondevs/Nova#109]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova 0.86, paper 1.18.1

### Observed/Actual behavior

I have a large build with over 200 storage units, tons about cable ect, in total  2235, when its running fine, but sometimes it will have 6533 Armor Stands from Nova, instead of 2235.(I get this from f3, standing in the same place) when 6533 is sent to the client the frame rate drops to 0, If I restart the server it goes back to 2235 and runs fine for some time. Theres nothing wrong with the server, tps, lag, ect.  I saw in the code that you use "fake armor stand" I was wonder if there was a bug that sends to many and/or a way to send only the ones in a range, to limit it. 

### Steps to reproduce

not sure how to reproduce.

**Comment by ByteZ1337** [comment]
You can lower your renderdistance using /nova renderdistance. Could you check your database if there are multiple tileentities at the same block?

**Comment by freethemice** [comment]
changing the renderdistance  didn't have any effect

**Comment by freethemice** [comment]
It was hard to do but they looked almost complete sold. My auto restart on my server happened and I couldn't cancel it in time, so i could get a screen shot.

**Comment by ByteZ1337** [comment]
> It was hard to do but they looked almost complete sold

Do you mean "solid"? If so, try enabling the ``chunk_reload_watcher`` in the config and see if it prints anything to the console.

**Comment by freethemice** [comment]
yes, will do

**Comment by freethemice** [comment]
`
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
at java.base/java.lang.Thread.run(Thread.java:833)
xyz.xenondevs.nova.world.ChunkReloadException: (This is not an error, you can disable this message in plugins/Nova/config/config.json)
Nova has detected a Chunk loading multiple times in a short timeframe.
ChunkPos(worldUUID=c2ab5842-c661-4bde-9eb6-41b83b0d927d, x=1, z=-312) | Reload #3
A stacktrace is attached for debugging purposes:
at Nova-0.8.6.jar//xyz.xenondevs.nova.world.ChunkReloadWatcher.handleChunkLoad(ChunkReloadWatcher.kt:38)
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor488.execute(Unknown Source)
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:809)
at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$20(PlayerChunk.java:679)
at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:195)
at net.minecraft.server.level.PlayerChunk.a(PlayerChunk.java:689)
at net.minecraft.server.level.ChunkMapDistance.a(ChunkMapDistance.java:146)
at net.minecraft.server.level.ChunkProviderServer.p(ChunkProviderServer.java:838)
at net.minecraft.server.level.ChunkMapDistance.addPriorityTicket(ChunkMapDistance.java:342)
at net.minecraft.server.level.ChunkMapDistance.markUrgent(ChunkMapDistance.java:293)
at net.minecraft.server.level.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:754)
at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:658)
at net.minecraft.world.level.World.a(World.java:531)
at net.minecraft.world.level.World.a_(World.java:865)
at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.getType(CraftBlock.java:218)
at Nova-0.8.6.jar//xyz.xenondevs.nova.tileentity.impl.world.BlockBreaker.handleTick(BlockBreaker.kt:68)
at Nova-0.8.6.jar//xyz.xenondevs.nova.tileentity.TileEntityManager$init$4.invoke(TileEntityManager.kt:95)
at Nova-0.8.6.jar//xyz.xenondevs.nova.tileentity.TileEntityManager$init$4.invoke(TileEntityManager.kt:95)
at Nova-0.8.6.jar//xyz.xenondevs.nova.util.SchedulerUtilsKt$runTaskTimerSynchronized$1.run(SchedulerUtils.kt:29)
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
11:32:15
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by freethemice** [comment]
I have a skyblock plugin that reloads all chunks to recalculate the island values, would that cause this?

**Comment by ByteZ1337** [comment]
Maybe. Could you test if it still happens without the plugin?

**Comment by freethemice** [comment]
I changed it from every 30 minutes to every second and the entity count and the messages shoot up really fast. I turned it completely off and so far its fine, and no messages in console.

**Comment by ByteZ1337** [comment]
What's the name of the plugin?

**Comment by freethemice** [comment]
[iridium-skyblock](https://www.spigotmc.org/resources/iridium-skyblock-1-13-1-18.62480/)
options called islandRecalculateInterval

**Comment by ByteZ1337** [comment]
Please actually test if this is caused by another plugin before selecting "This bug also occurs when no other plugins are present." next time

**Comment by freethemice** [comment]
No problem. Thanks for your patients and help.

**Comment by ByteZ1337** [comment]
Could you send me your world? (and updated nova database file if anything changed)

**Comment by freethemice** [comment]
Sure, I get off work in 2 hrs, illl post it then

**Comment by freethemice** [comment]
[http://play.firesoftitan.com/freethemice.zip](http://play.firesoftitan.com/freethemice.zip) 
here is the world with nova folder and IridiumSkyblock folder
I have the option turn off at 0, Also, since turning it off I haven't had any problems

**Comment by CivicXFB** [comment]
Dear freethemice can you provide an optimisation? Now facing the same problem as you did before, thank you

**Comment by freethemice** [comment]
I had to change the render distances in nova all the way down, but it still super low frame rates. Storage units are the problem because they only hold one item, if they change it to hold multiple items, and/or change it to petrified slab, so they won't have to use armor stands, I think that would fix it.

**Comment by CivicXFB** [comment]
I've adjusted the rendering distance to 1, but it still doesn't help in those mechanical areas
