### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PixelABPlus** [xenondevs/Nova#127]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova-0.8.11, PurPur-1.18.2-1609

### Steps to reproduce

1.Place Nova
2.Place Towny
3.Start Server

### Errors
```

[05:23:12 WARN]: [Nova] Task #641 for Nova v0.8.11 generated an exception
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863) ~[guava-31.0.1-jre.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager.canBreak(ProtectionManager.kt:46) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.tileentity.impl.world.Quarry.selectNextDestination(Quarry.kt:368) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.tileentity.impl.world.Quarry.handleTick(Quarry.kt:240) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$4.invoke(TileEntityManager.kt:95) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$4.invoke(TileEntityManager.kt:95) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.util.SchedulerUtilsKt$runTaskTimerSynchronized$1.run(SchedulerUtils.kt:29) ~[Nova-0.8.11.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at com.palmergames.bukkit.towny.object.PlayerCache.getBlockPermission(PlayerCache.java:172) ~[Towny-0.98.1.5.jar:?]
        at com.palmergames.bukkit.towny.object.PlayerCache.getDestroyPermission(PlayerCache.java:140) ~[Towny-0.98.1.5.jar:?]
        at com.palmergames.bukkit.towny.object.PlayerCache.getCachePermission(PlayerCache.java:98) ~[Towny-0.98.1.5.jar:?]
        at com.palmergames.bukkit.towny.utils.PlayerCacheUtil.getCachePermission(PlayerCacheUtil.java:100) ~[Towny-0.98.1.5.jar:?]
        at xyz.xenondevs.nova.integration.protection.plugin.Towny.hasPermission(Towny.kt:37) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.integration.protection.plugin.Towny.canBreak(Towny.kt:19) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.api.protection.ProtectionIntegration.canBreak(ProtectionIntegration.kt:20) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager$canBreak$1$1.invoke(ProtectionManager.kt:48) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager$canBreak$1$1.invoke(ProtectionManager.kt:48) ~[Nova-0.8.11.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager.checkIntegrations(ProtectionManager.kt:120) ~[NNova-0.8.11.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager.canBreak$lambda-2(ProtectionManager.kt:48) ~[Nova-0.8.11.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar:?]
        ... 16 more
[05:23:12 WARN]: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
[05:23:12 WARN]:        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
[05:23:12 WARN]:        at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
[05:23:12 WARN]:        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)\
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.integration.protection.ProtectionManager.canUseBlock(ProtectionManager.kt:58)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl.hasAccessPermission(NetworkManager.kt:375)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl.handleBridgeAdd(NetworkManager.kt:241)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.tileentity.impl.energy.Cable$handleInitialized$1.invoke(Cable.kt:103)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.tileentity.impl.energy.Cable$handleInitialized$1.invoke(Cable.kt:103)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl$init$2.invoke(NetworkManager.kt:110)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl$init$2.invoke(NetworkManager.kt:106)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.util.AsyncExecutor.run$lambda-0(SchedulerUtils.kt:80)
[05:23:12 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[05:23:12 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[05:23:12 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[05:23:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[05:23:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[05:23:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[05:23:12 WARN]: Caused by: java.lang.NullPointerException
[05:23:12 WARN]:        at Towny-0.98.1.5.jar//com.palmergames.bukkit.towny.object.PlayerCache.getBlockPermission(PlayerCache.java:172)
[05:23:12 WARN]:        at Towny-0.98.1.5.jar//com.palmergames.bukkit.towny.object.PlayerCache.getSwitchPermission(PlayerCache.java:145)
[05:23:12 WARN]:        at Towny-0.98.1.5.jar//com.palmergames.bukkit.towny.object.PlayerCache.getCachePermission(PlayerCache.java:101)
[05:23:12 WARN]:        at Towny-0.98.1.5.jar//com.palmergames.bukkit.towny.utils.PlayerCacheUtil.getCachePermission(PlayerCacheUtil.java:100)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.integration.protection.plugin.Towny.hasPermission(Towny.kt:37)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.integration.protection.plugin.Towny.canUseBlock(Towny.kt:25)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.api.protection.ProtectionIntegration.canUseBlock(ProtectionIntegration.kt:42)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.integration.protection.ProtectionManager$canUseBlock$1$1.invoke(ProtectionManager.kt:60)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.integration.protection.ProtectionManager$canUseBlock$1$1.invoke(ProtectionManager.kt:60)
[05:23:12 WARN]:        atNova-0.8.11.jar//xyz.xenondevs.nova.integration.protection.ProtectionManager.checkIntegrations(ProtectionManager.kt:120)
[05:23:12 WARN]:        at Nova-0.8.11.jar//xyz.xenondevs.nova.integration.protection.ProtectionManager.canUseBlock$lambda-4(ProtectionManager.kt:60)
[05:23:12 WARN]:        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
[05:23:12 WARN]:        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
[05:23:12 WARN]:        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
[05:23:12 WARN]:        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
[05:23:12 WARN]:        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
[05:23:12 WARN]:        ... 16 more
```

### Additional context

Is Nova incompatibility with Towny?

**Comment by NichtStudioCode** [comment]
I cannot reproduce the issue with the above-mentioned steps.
This also seems to be more of an issue with Towny than Nova, and you should probably report it to the Towny developers.
