### ISSUE TITLE
[Bug] Autdated version of Nova.

### ISSUE THREAD

**Issue by ErythroCraft** [xenondevs/Nova#133]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.8.12 | spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3

### Expected behavior

After updating spigot jar fil with BuildTools your Plugin generates an Erros at the server consol.

### Observed/Actual behavior

I actually saw an error.

### Steps to reproduce

1. updating spigot with build tools
2. starting server
3. error since three days

### Errors

[17:35:08] [Server thread/WARN]: [Nova] Task #1279 for Nova v0.8.12 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.syncCommands(CraftServer.java:478) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
        at xyz.xenondevs.nova.command.CommandManager.registerCommand(CommandManager.kt:48) ~[?:?]
        at xyz.xenondevs.nova.command.CommandManager.registerCommands(CommandManager.kt:31) ~[?:?]
        at xyz.xenondevs.nova.command.CommandManager.init(CommandManager.kt:26) ~[?:?]
        at xyz.xenondevs.nova.initialize.Initializable$initialize$1.invoke(Initializable.kt:19) ~[?:?]
        at xyz.xenondevs.nova.initialize.Initializable$initialize$1.invoke(Initializable.kt:18) ~[?:?]
        at xyz.xenondevs.nova.util.SchedulerUtilsKt$sam$i$java_lang_Runnable$0.run(SchedulerUtils.kt) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1285) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Additional context

please update you repo

**Comment by ErythroCraft** [comment]
fixed
