### ISSUE TITLE
[Bug] When the server has been running for a while, the server will crash

### ISSUE THREAD

**Issue by CivicXFB** [xenondevs/Nova#135]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

nova:0.8.12 PurPur-1.18.2-1863

### Expected behavior

I've checked several configurations and allocated 5GRAM to him and it still doesn't work perfectly!It used to run fine on 4G RAM to 5G with frequent storage problems, I can't understand why this would be done

### Observed/Actual behavior

It keeps falling apart. Crashes every few hours

### Steps to reproduce

null

### Errors

[07:46:17] [Async Nova Worker - 150/WARN]: java.lang.OutOfMemoryError
[07:46:17] [Async Nova Worker - 150/WARN]: 	at java.base/java.util.zip.Deflater.init(Native Method)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at java.base/java.util.zip.Deflater.<init>(Deflater.java:201)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at java.base/java.util.zip.Deflater.<init>(Deflater.java:210)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at Nova-0.8.12.jar//xyz.xenondevs.nova.util.data.BinaryUtilsKt.compress(BinaryUtils.kt:43)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at Nova-0.8.12.jar//xyz.xenondevs.nova.util.data.BinaryUtilsKt.compress$default(BinaryUtils.kt:42)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at Nova-0.8.12.jar//xyz.xenondevs.nova.data.database.columtype.CompoundColumnType.valueToDB(CompoundColumnType.kt:19)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:12)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:52)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:144)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:130)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at Nova-0.8.12.jar//net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert(ExposedUpsertExtensions.kt:17)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at Nova-0.8.12.jar//net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert$default(ExposedUpsertExtensions.kt:11)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at Nova-0.8.12.jar//xyz.xenondevs.nova.tileentity.TileEntityManager$saveChunk$statement$1.invoke(TileEntityManager.kt:247)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at Nova-0.8.12.jar//xyz.xenondevs.nova.tileentity.TileEntityManager$saveChunk$statement$1.invoke(TileEntityManager.kt:243)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214)
[07:46:17] [Async Nova Worker - 150/WARN]: 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165)

### Additional context

[08:40:52 INFO]: Plugins (64): ajLeaderboards, antiRedstoneClock, AureliumSkills, AuthMe, BBSToper*, Cartographer2, Citizens, CMI, CMIEInjector*, CMILib, CoreProtect, CrazyAuctionsPlus, Dantiao, DisplayShops, eBackup, eco, EcoEnchants, ExcellentCrates, FirstJoinEvents, GPS, HolographicDisplays, Infiniteannouncements, InteractiveBoard, IridiumSkyblock, ItemNBTEdit, ItemsAdder, LiteBans, LoneLibs, LuckPerms, MinePay, MMOBars, MMOItems, MobFarmManager, Multiverse-Core, MythicLib, NexEngine, Nova, PlaceholderAPI, PlayerParticles, PlayerPoints, ProtocolLib, PyroFishingPro, PyroLib, RealisticSeasons, ServerTours, Shopkeepers, SuperLobby, TAB, TAB-Bridge, ThirstBar, TradeMe, TrChat, TrElytra, TrMenu, UltimateAutoRestart, UltimateTimber, Vault, ViaBackwards, ViaVersion, VillagerTradeLimiter, VipSystem, voicechat, Vulcan, Winds net.minecraft.server.level.EntityPlayer

**Comment by NichtStudioCode** [comment]
Hi, you've selected that this issue occurs with no other plugins on the server, but there are 63 other plugins running on it.

You're free to open a new issue once you've confirmed that the problem persists with no other plugins on the server.
