### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Hugytor09YT** [xenondevs/Nova#14]
**Describe the bug**
I started the server and i get this error

**To Reproduce**
1. Start the server

**Errors**
```
[09:11:10] [Server thread/WARN]: [Nova] Task #49 for Nova v0.2.1 generated an exception
java.lang.NullPointerException: null
        at xyz.xenondevs.nova.ability.JetpackFlyAbility.handleTick(JetpackFlyAbility.kt:36) ~[?:?]
        at xyz.xenondevs.nova.ability.AbilityManager$init$2.invoke(AbilityManager.kt:31) ~[?:?]
        at xyz.xenondevs.nova.ability.AbilityManager$init$2.invoke(AbilityManager.kt:30) ~[?:?]
        at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTaskTimer$lambda-2(SchedulerUtils.kt:13) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[Discord.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[Discord.jar:3170-Spigot-a483d2c-ec116f6]
```

**Comment by NichtStudioCode** [comment]
Was this the first time you started the server with Nova?
Did you update from a previous version?
Did you use the Jetpack previously?

**Comment by Hugytor09YT** [comment]
1. 12/07/2021 (DD/MM/YYYY)
2. No (1.17 every time) and the plugin Nova was updated BUT i removed the folder and the armor stands back to updating the plugin
3. Yes.
