### ISSUE TITLE
Exception occurred trying to initialize xyz.xenondevs.nova.data.resources.Resources

### ISSUE THREAD

**Issue by trekinsanity** [xenondevs/Nova#144]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova:  0.9,Paper version git-Paper-29

### Observed/Actual behavior

Nova doesn't load.
Get error on paper server with ONLY Nova installed. (See below for error.)

### Steps to reproduce

start  server.
Get error before anyone is logged in.

### Errors

[19:01:11 ERROR]: [Nova] An exception occurred trying to initialize xyz.xenondevs.nova.data.resources.Resources@78cdce4
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:66) ~[gson-2.8.9.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.LanguageContent.addFromPack(LanguageContent.kt:18) ~[Nova-0.9.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.create(ResourcePackBuilder.kt:41) ~[Nova-0.9.jar:?]
	at xyz.xenondevs.nova.data.resources.Resources.createResourcePack(Resources.kt:52) ~[Nova-0.9.jar:?]
	at xyz.xenondevs.nova.data.resources.Resources.init$Nova(Resources.kt:44) ~[Nova-0.9.jar:?]
	at xyz.xenondevs.nova.initialize.Initializable.initialize(Initializable.kt:29) ~[Nova-0.9.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer$init$1$1$1.invoke(Initializer.kt:66) ~[Nova-0.9.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer$init$1$1$1.invoke(Initializer.kt:63) ~[Nova-0.9.jar:?]
	at xyz.xenondevs.nova.util.AsyncExecutor.run$lambda-0(SchedulerUtils.kt:88) ~[Nova-0.9.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:541) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:61) ~[gson-2.8.9.jar:?]
	... 14 more

**Comment by NichtStudioCode** [comment]
This was caused by a corrupted download and should already be fixed. Redownload Nova and try again.
