### ISSUE TITLE
[Bug] log4j error

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#177]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova Version: 0.11.2;git-Paper-132 (MC: 1.19.2) 

### Nova Addons and Versions

null

### Expected behavior

[Uploading latest.log…]()

### Observed/Actual behavior

[Uploading latest.log…]()

### Steps to reproduce

1. Start server

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/9540443/latest.log)

**Comment by ByteZ1337** [comment]
There is no error in your log

**Comment by xiaozhangup** [comment]
> There is no error in your log

Maybe because this is a log4j error, I can only see it in the console and not in the file. If I encounter the problem next time I will take a screenshot of the console content and send it to you

**Comment by ByteZ1337** [comment]
Someone else sent us the stacktrace
```
 2022-09-10 20:01:25,076 Server thread ERROR An exception occurred processing Appender Async org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.LinkageError: loader java.net.URLClassLoader @1bb0177c attempted duplicate class definition for xyz.xenondevs.nova.util.SchedulerUtilsKt. (xyz.xenondevs.nova.util.SchedulerUtilsKt is in unnamed module of loader java.net.URLClassLoader @1bb0177c, parent loader 'Nova-0.11.2.jar' @4dd05adb)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:750)
        at org.bukkit.craftbukkit.v1_19_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:32)
        at java.logging/java.util.logging.Logger.log(Logger.java:980)
        at java.logging/java.util.logging.Logger.doLog(Logger.java:1007)
        at java.logging/java.util.logging.Logger.log(Logger.java:1118)
        at xyz.xenondevs.nova.initialize.Initializable.initialize$performInitialization(Initializable.kt:29)
        at xyz.xenondevs.nova.initialize.Initializable.access$initialize$performInitialization(Initializable.kt:9)
        at xyz.xenondevs.nova.initialize.Initializable$initialize$1.invoke(Initializable.kt:36)
        at xyz.xenondevs.nova.initialize.Initializable$initialize$1.invoke(Initializable.kt:36)
        at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTask$lambda-1(SchedulerUtils.kt:25)
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1493)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1417)
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1193)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.LinkageError: loader java.net.URLClassLoader @1bb0177c attempted duplicate class definition for xyz.xenondevs.nova.util.SchedulerUtilsKt. (xyz.xenondevs.nova.util.SchedulerUtilsKt is in unnamed module of loader java.net.URLClassLoader @1bb0177c, parent loader 'Nova-0.11.2.jar' @4dd05adb)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at xyz.xenondevs.nova.transformer.PatchedClassLoader.loadClass(PatchedClassLoader.kt:15)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:574)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:171)
        at org.apache.logging.log4j.core.impl.ThrowableProxyHelper.loadClass(ThrowableProxyHelper.java:214)
        at org.apache.logging.log4j.core.impl.ThrowableProxyHelper.toExtendedStackTrace(ThrowableProxyHelper.java:112)
        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:112)
        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:96)
        at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:347)
        at org.apache.logging.log4j.core.impl.Log4jLogEvent$LogEventProxy.<init>(Log4jLogEvent.java:970)
        at org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:745)
        at org.apache.logging.log4j.core.impl.Log4jLogEvent.createMemento(Log4jLogEvent.java:796)
        at org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        ... 32 more
```
