### ISSUE TITLE
[Bug] Logistics can sometimes get out of hand

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#185]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

0.11.6 git-Mirai-23 (MC: 1.19.2)

### Nova Addons and Versions

L0.2 M0.2.1 J0.1.4

### Expected behavior

[00:51:22] [Nova NetworkManager/ERROR]: [Nova] An exception occurred in a NetworkManager task
java.lang.NullPointerException: null
	at xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl.recalculateNetworks(NetworkManager.kt:752) ~[?:?]
	at xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl.removeBridge(NetworkManager.kt:679) ~[?:?]
	at xyz.xenondevs.nova.tileentity.network.NetworkManager$DefaultImpls.removeBridge$default(NetworkManager.kt:63) ~[?:?]
	at xyz.xenondevs.nova.logistics.tileentity.Cable$handleRemoved$2.invoke(Cable.kt:148) ~[?:?]
	at xyz.xenondevs.nova.logistics.tileentity.Cable$handleRemoved$2.invoke(Cable.kt:148) ~[?:?]
	at xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl$init$2.invoke(NetworkManager.kt:204) ~[?:?]
	at xyz.xenondevs.nova.tileentity.network.NetworkManagerImpl$init$2.invoke(NetworkManager.kt:191) ~[?:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) ~[?:?]

### Observed/Actual behavior

1.Logistics nodes turned into chains

### Steps to reproduce

Not sure that this will happen at any time. Usually only a few will be affected

### Full server log
[2022-10-18-19.log](https://github.com/xenondevs/Nova/files/9815745/2022-10-18-19.log)
[2022-10-19-1.log](https://github.com/xenondevs/Nova/files/9815738/2022-10-19-1.log)

### Errors

[00:53:12] [Server thread/ERROR]: [Nova] Failed to initialize NovaTileEntityState(pos=BlockPos(world=CraftWorld{name=IridiumSkyblock}, x=-1156, y=95, z=-4817), id=logistics:ultimate_cable, uuid=de2bebee-2685-4430-8f8a-282a90e5c00c, ownerUUID=8a934169-31be-3733-b0a7-87c614ad79e5, data={
  "attachments": []
  "modelId": 40
  "bridgeFaces": [DOWN, UP, NORTH, SOUTH, WEST, EAST]
  "connectedNodes": {}
  "global": {
  }
  "networks": {}
})
java.lang.IllegalStateException: This FakeEntity is already registered
	at xyz.xenondevs.nova.world.fakeentity.FakeEntity.register(FakeEntity.kt:60) ~[?:?]
	at xyz.xenondevs.nova.world.block.model.ArmorStandModelProvider.load(ArmorStandModelProvider.kt:54) ~[?:?]
	at xyz.xenondevs.nova.data.world.block.state.NovaBlockState.handleInitialized(NovaBlockState.kt:45) ~[?:?]
	at xyz.xenondevs.nova.data.world.block.state.NovaTileEntityState.handleInitialized(NovaTileEntityState.kt:62) ~[?:?]
	at xyz.xenondevs.nova.data.world.WorldDataManager$loadChunk$1.invoke(WorldDataManager.kt:76) ~[?:?]
	at xyz.xenondevs.nova.data.world.WorldDataManager$loadChunk$1.invoke(WorldDataManager.kt:72) ~[?:?]
	at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTask$lambda-1(SchedulerUtils.kt:25) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[mirai-1.19.2.jar:git-Mirai-23]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1487) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:451) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1411) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1182) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[mirai-1.19.2.jar:git-Mirai-23]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:53:12] [Server thread/ERROR]: [Nova] Failed to initialize NovaTileEntityState(pos=BlockPos(world=CraftWorld{name=IridiumSkyblock}, x=-1156, y=94, z=-4817), id=logistics:ultimate_cable, uuid=765f2df2-a188-4b6d-a452-3e7469393d47, ownerUUID=8a934169-31be-3733-b0a7-87c614ad79e5, data={
  "attachments": []
  "modelId": 20
  "bridgeFaces": [DOWN, UP, NORTH, SOUTH, WEST, EAST]
  "connectedNodes": {}
  "global": {
  }
  "networks": {}
})
java.lang.IllegalStateException: This FakeEntity is already registered
	at xyz.xenondevs.nova.world.fakeentity.FakeEntity.register(FakeEntity.kt:60) ~[?:?]
	at xyz.xenondevs.nova.world.block.model.ArmorStandModelProvider.load(ArmorStandModelProvider.kt:54) ~[?:?]
	at xyz.xenondevs.nova.data.world.block.state.NovaBlockState.handleInitialized(NovaBlockState.kt:45) ~[?:?]
	at xyz.xenondevs.nova.data.world.block.state.NovaTileEntityState.handleInitialized(NovaTileEntityState.kt:62) ~[?:?]
	at xyz.xenondevs.nova.data.world.WorldDataManager$loadChunk$1.invoke(WorldDataManager.kt:76) ~[?:?]
	at xyz.xenondevs.nova.data.world.WorldDataManager$loadChunk$1.invoke(WorldDataManager.kt:72) ~[?:?]
	at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTask$lambda-1(SchedulerUtils.kt:25) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[mirai-1.19.2.jar:git-Mirai-23]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1487) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:451) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1411) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1182) ~[mirai-1.19.2.jar:git-Mirai-23]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[mirai-1.19.2.jar:git-Mirai-23]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by xiaozhangup** [comment]
Is 0.12.0 still far away?

**Comment by NichtStudioCode** [comment]
> This issue is about a specific plugin incompatibility.

What plugin are we talking about here?

**Comment by xiaozhangup** [comment]
> > This issue is about a specific plugin incompatibility.
> 
> What plugin are we talking about here?

My terrible English, sorry, I misunderstood the phrase at the time.This is not an incompatibility with a specific plugin, but a general problem.
(Applies to the three Issues you just replied to me)

**Comment by NichtStudioCode** [comment]
Well, the general idea behind that selection box is that you check which plugin is causing the issue, or if this issue occurs without any other plugins present on the server. Based on your log file, I can see that there are a lot of plugins running on your server. Sadly, we do not have the resources to test every plugin combination for every report, so that's something you'd need to do.
