### ISSUE TITLE
[Bug] Some Error

### ISSUE THREAD

**Issue by xiaozhangup** [xenondevs/Nova#188]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

0.11.7 Purpur

### Nova Addons and Versions

L0.2 M0.2.1 J0.1.4

### Observed/Actual behavior

Some warn in console

### Steps to reproduce

No

### Full server log

[11:21:04] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to Nova v0.11.7
java.lang.IllegalStateException: Attachments cannot be added to dead players
	at xyz.xenondevs.nova.player.attachment.AttachmentManager.addAttachment(AttachmentManager.kt:49) ~[nova16552597114022102935.jar:?]
	at xyz.xenondevs.nova.player.attachment.AttachmentManager.activateAttachments(AttachmentManager.kt:123) ~[nova16552597114022102935.jar:?]
	at xyz.xenondevs.nova.player.attachment.AttachmentManager.activateAttachments(AttachmentManager.kt:115) ~[nova16552597114022102935.jar:?]
	at xyz.xenondevs.nova.player.attachment.AttachmentManager.handleRespawn(AttachmentManager.kt:93) ~[nova16552597114022102935.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:git-petal-"0e80f26"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:936) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:839) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:834) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleClientCommand(ServerGamePacketListenerImpl.java:3143) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.handle(ServerboundClientCommandPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.a(ServerboundClientCommandPacket.java:10) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[petal-1.19.2.jar:git-petal-"0e80f26"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NichtStudioCode** [comment]
> This issue is about a specific plugin incompatibility.

What plugin are we talking about here?


Your report is also missing proper steps to reproduce, server and plugin version.
