### ISSUE TITLE
Addons    File header and local file header mismatch

### ISSUE THREAD

**Issue by xiaotangaa** [xenondevs/Nova#204]
### Describe your feature request.

These errors occur when I add extensions and my server restarts automatically

### Additional context

[15:58:26] [Server thread/INFO]: [Nova] Loading default config
[15:58:26] [Server thread/INFO]: [Nova] Registering packet handlers
[15:58:26] [Server thread/INFO]: [Nova] Loading Addons...
[15:58:26] [Server thread/INFO]: [Nova] [Jetpacks] Loaded Jetpacks [jetpacks] v0.1.6
[15:58:26] [Server thread/INFO]: [Nova] [Logistics] Loaded Logistics [logistics] v0.2.2
[15:58:26] [Server thread/INFO]: [Nova] [Machines] Loaded Machines [machines] v0.3.1
[15:58:26] [Server thread/INFO]: [Nova] Applying patches...
[15:58:27] [Server thread/INFO]: [Nova] Building resource pack
[15:58:28] [Server thread/ERROR]: [Nova] An exception occurred trying to initialize xyz.xenondevs.nova.data.resources.ResourceGeneration$PreWorld@1bdcc0e4
net.lingala.zip4j.exception.ZipException: File header and local file header mismatch
	at net.lingala.zip4j.tasks.AbstractExtractFileTask.verifyNextEntry(AbstractExtractFileTask.java:162) ~[zip4j-2.11.1.jar:?]
	at net.lingala.zip4j.tasks.AbstractExtractFileTask.extractFile(AbstractExtractFileTask.java:54) ~[zip4j-2.11.1.jar:?]
	at net.lingala.zip4j.tasks.ExtractAllFilesTask.executeTask(ExtractAllFilesTask.java:41) ~[zip4j-2.11.1.jar:?]
	at net.lingala.zip4j.tasks.ExtractAllFilesTask.executeTask(ExtractAllFilesTask.java:17) ~[zip4j-2.11.1.jar:?]
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:51) ~[zip4j-2.11.1.jar:?]
	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:45) ~[zip4j-2.11.1.jar:?]
	at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:470) ~[zip4j-2.11.1.jar:?]
	at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:441) ~[zip4j-2.11.1.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.basepack.BasePacks.include(BasePacks.kt:42) ~[Nova-0.12.4.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.buildPackPreWorld(ResourcePackBuilder.kt:111) ~[Nova-0.12.4.jar:?]
	at xyz.xenondevs.nova.data.resources.ResourceGeneration$PreWorld.init$nova(ResourceGeneration.kt:63) ~[Nova-0.12.4.jar:?]
	at xyz.xenondevs.nova.initialize.Initializable.initialize(Initializable.kt:19) ~[Nova-0.12.4.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:105) ~[Nova-0.12.4.jar:?]
	at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:75) ~[Nova-0.12.4.jar:?]
	at xyz.xenondevs.nova.loader.NovaLoader.onEnable(NovaLoader.java:33) ~[Nova-0.12.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-270]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-270]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-270]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-270]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-270]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:58:28] [Server thread/INFO]: [Nova] Loading configs
[15:58:28] [Server thread/WARN]: [Nova] Skipping initialization: xyz.xenondevs.nova.addon.AddonsInitializer
[15:58:28] [Server thread/WARN]: [Nova] Shutting down the server...

**Comment by NichtStudioCode** [comment]
Not a feature request.
