### ISSUE TITLE
[Bug] java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by 1Chaos71** [xenondevs/Nova#230]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Paper 1.19.3-BUILD-368 / Nova 0.12.15 

### Nova Addons and Versions

Logistic v0.2.3 / Jetpacks v0.1.7 / Mashines 0.3.2

### Observed/Actual behavior

Waila will remain displayed even if you are not looking at anything, but as soon as you look at a block/point again, it will also update normally.

### Steps to reproduce

Error is not always present ... can not always reproduce it

### Full server log

[Nova] Task #745 for Nova v0.12.15 generated an exception
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170) ~[kotlin-stdlib-1.7.21.jar:1.7.21-release-272(1.7.21)]
at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) ~[kotlin-stdlib-1.7.21.jar:1.7.21-release-272(1.7.21)]
at xyz.xenondevs.nova.ui.overlay.bossbar.BossBarOverlayManager.getEndY(BossBarOverlayManager.kt:310) ~[Nova-0.12.15.jar:?]
at xyz.xenondevs.nova.ui.overlay.bossbar.FakeBossBarOverlay.getY(FakeBossBarOverlay.kt:53) ~[Nova-0.12.15.jar:?]
at xyz.xenondevs.nova.ui.overlay.bossbar.FakeBossBarOverlay.getBarLevel(FakeBossBarOverlay.kt:63) ~[Nova-0.12.15.jar:?]
at xyz.xenondevs.nova.ui.overlay.bossbar.BossBarOverlayManager.remakeBars(BossBarOverlayManager.kt:148) ~[Nova-0.12.15.jar:?]
at xyz.xenondevs.nova.ui.overlay.bossbar.BossBarOverlayManager.handleTick(BossBarOverlayManager.kt:134) ~[Nova-0.12.15.jar:?]
at xyz.xenondevs.nova.ui.overlay.bossbar.BossBarOverlayManager.access$handleTick(BossBarOverlayManager.kt:39) ~[Nova-0.12.15.jar:?]
at xyz.xenondevs.nova.ui.overlay.bossbar.BossBarOverlayManager$reload$2.invoke(BossBarOverlayManager.kt:67) ~[Nova-0.12.15.jar:?]
at xyz.xenondevs.nova.ui.overlay.bossbar.BossBarOverlayManager$reload$2.invoke(BossBarOverlayManager.kt:67) ~[Nova-0.12.15.jar:?]
at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTaskTimer$lambda$2(SchedulerUtils.kt:28) ~[Nova-0.12.15.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-368]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-368]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-368]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-368]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-368]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-368]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-368]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NichtStudioCode** [comment]
Please actually submit the full server log

**Comment by 1Chaos71** [comment]
Sorry that it took so long. here is my log from 24.1. although a different task number but otherwise everything looks the same (for me as a layman)
"Error" appears from [18:02:38] and continues until [19:15:59].
https://chaosbot.de/_extras/2023-01-24-5.log

**Comment by 1Chaos71** [comment]
I have just received more info on the process possibly reproduction

We have an elevator plugin:
( https://www.spigotmc.org/resources/simple-elevators-1-8-1-19.44462/ ) 
The bossbar is used as a floor display.
As soon as Waila freezes the last floor display (mixed with Waila) freezes ... as soon as I have a photo I can share it here if needed.

**Comment by NichtStudioCode** [comment]
Will be fixed in `0.13`.
