### ISSUE TITLE
Nova broke ItemsAdder's Custom Armor

### ISSUE THREAD

**Issue by Teenkung123** [xenondevs/Nova#246]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [x] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova v0.13-alpha.9, purpur-1.19.4-1962, ItemsAdder_3.4.1-r6_1

### Nova Addons and Versions

No Addons

### Expected behavior

ItemsAdder's Custom Armor should work properly when resource pack gets generated by Nova

### Observed/Actual behavior

Nova break ItemsAdder's Custom Armor Model after running /nova resourcepack create

### Steps to reproduce

1. Download and install Purpur 1.19.4
2. Install Nova and ItemsAdder
3. Add Custom Armor to ItemsAdder
4. Try Use ItemsAdder's resource pack to see is armor model is broken or not
![image](https://user-images.githubusercontent.com/51858378/236507945-c415bb4e-2163-4ca1-8d6b-31354f955cb0.png)

5. Enable no-host for ItemsAdder
6. Config nova and add ItemsAdder's Resource pack as base pack
7. Config auto_upload on nova's config
8. Let nova generate it's resource pack and apply it
9. Look at the Custom Armor Model again
![image](https://user-images.githubusercontent.com/51858378/236510315-0b7cbdb0-3cf8-4ddd-bcac-5018977b8768.png)

### Full server log

There are 2 logs since I restart the server because I messed up with config (forgot to enable auto_upload)

1. https://pastebin.com/JcDbYS1K
2. https://pastebin.com/nfM9r9XB

### Errors

got this error sometimes but it does not related to Custom Armors

```
[23:05:03 ERROR]: [Nova] An exception occurred while handling a clientbound packet.
java.lang.ClassCastException: class net.kyori.adventure.text.TranslatableComponentImpl cannot be cast to class net.kyori.adventure.text.Component (net.kyori.adventure.text.TranslatableComponentImpl is in unnamed module of loader java.net.URLClassLoader @58d25a40; net.kyori.adventure.text.Component is in unnamed module of loader xyz.xenondevs.nova.loader.NovaClassLoader @532b7dc5)
        at xyz.xenondevs.nmsutils.network.event.clientbound.ClientboundSystemChatPacketEvent.<init>(ClientboundSystemChatPacketEvent.kt:26) ~[nms-utilities-0.9.jar:?]
        at xyz.xenondevs.nmsutils.network.event.PacketEventManager$1.invoke(PacketEventManager.kt:52) ~[nms-utilities-0.9.jar:?]
        at xyz.xenondevs.nmsutils.network.event.PacketEventManager$1.invoke(PacketEventManager.kt:52) ~[nms-utilities-0.9.jar:?]
        at xyz.xenondevs.nmsutils.network.event.PacketEventManager.createAndCallEvent$nms_utilities(PacketEventManager.kt:94) ~[nms-utilities-0.9.jar:?]
        at xyz.xenondevs.nmsutils.network.PacketHandler.callEvent(PacketHandler.kt:105) ~[nms-utilities-0.9.jar:?]
        at xyz.xenondevs.nmsutils.network.PacketHandler.write(PacketHandler.kt:46) ~[nms-utilities-0.9.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:466) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:440) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by NichtStudioCode** [comment]
Works fine for me. (Example armor from the [ItemsAdder Wiki](https://itemsadder.devs.beer/plugin-usage/adding-content/armors/custom-textured-armor))
![image](https://user-images.githubusercontent.com/51272202/236628371-50bad941-cf45-4227-8796-b63a9b415570.png)

**Comment by Teenkung123** [comment]
Hmm, that's weird because ItemsAdder's resource pack is working fine, but when Nova merges it with its own pack, it just breaks. Is it possible for me to send you my test server files, and you try to replicate the issue?

**Comment by NichtStudioCode** [comment]
> Is it possible for me to send you my test server files, and you try to replicate the issue?

sure

**Comment by Teenkung123** [comment]
Thanks! Here's the server file:
https://bit.ly/3nzoght

**Comment by NichtStudioCode** [comment]
Please upload your file to a server that has an upload speed of more than 100Kb/s

**Comment by Teenkung123** [comment]
Sorry. here the new one: https://drive.google.com/file/d/1h7dGB0aTM4mHejBW4SRz7d5LE17NgHjI/view?usp=sharing
