### ISSUE TITLE
Nova thrown Warning on specific ItemsAdder API

### ISSUE THREAD

**Issue by Teenkung123** [xenondevs/Nova#248]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova v0.13-alpha.12, ItemsAdder 3.4.1b, purpur-1.19.4-1962

### Nova Addons and Versions

No Addons

### Observed/Actual behavior

I have a Furniture Shop plugin that generates a preview of furniture every 1 second at the same location and deletes the old one using the [ItemsAdder CustomFurniture API](https://lonedev6.github.io/API-ItemsAdder/). However, after the plugin generates a preview of the furniture, it throws a NullPointerException: "event.player must not be null" in Nova's plugin class [EventPreventionPatch.kt line 38](https://github.com/xenondevs/Nova/blob/main/nova/src/main/kotlin/xyz/xenondevs/nova/transformer/patch/misc/EventPreventionPatch.kt#L38).

### Steps to reproduce

Since it's my plugin specific on the server I will provide my test server that have the error, it will be easier to setup more than trying to reproduce:
https://drive.google.com/file/d/1sOfG7cjZuilQA4YBuYdyxV7VhFcXAxdc/view?usp=sharing

After installed follow this steps:
1. Enter the server
2. check console for error
3. try delete Nova
4. restart the server
5. enter the server again then look at console

### Full server log

https://pastebin.com/xmP7Hyvh

### Errors

```
[Server thread/WARN]: [FurnitureShop] Task #30 for FurnitureShop v1.0-SNAPSHOT generated an exception
java.lang.NullPointerException: event.player must not be null
	at xyz.xenondevs.nova.transformer.patch.misc.EventPreventionPatch.shouldPreventEvent(EventPreventionPatch.kt:38) ~[Nova-0.13-alpha.12.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at ia.m.kR.a(SourceFile:68) ~[ItemsAdder_3.4.1-r6_1.jar:?]
	at ia.m.br.a(SourceFile:254) ~[ItemsAdder_3.4.1-r6_1.jar:?]
	at ia.m.br.a(SourceFile:358) ~[ItemsAdder_3.4.1-r6_1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftRegionAccessor.addEntity(CraftRegionAccessor.java:545) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at org.bukkit.craftbukkit.v1_19_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:524) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at org.bukkit.craftbukkit.v1_19_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:518) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at org.bukkit.craftbukkit.v1_19_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:509) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at ia.m.br.a(SourceFile:328) ~[ItemsAdder_3.4.1-r6_1.jar:?]
	at ia.m.br.a(SourceFile:253) ~[ItemsAdder_3.4.1-r6_1.jar:?]
	at ia.m.br.a(SourceFile:154) ~[ItemsAdder_3.4.1-r6_1.jar:?]
	at dev.lone.itemsadder.api.CustomFurniture.spawnPreciseNonSolid(SourceFile:71) ~[ItemsAdder_3.4.1-r6_1.jar:?]
	at com.develop.devfurniture.Utils.PreviewItem.addPreviewItem(PreviewItem.java:18) ~[DevFurniture-1.0-SNAPSHOT-all.jar:?]
	at com.develop.devfurniture.Utils.TaskRunner.lambda$RunRandomFurnitureTask$0(TaskRunner.java:35) ~[DevFurniture-1.0-SNAPSHOT-all.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1962]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by NichtStudioCode** [comment]
I can add a null check there, but this is definitely an ItemsAdder issue. `PlayerEvent#getPlayer` is annotated with `@NotNull`, but ItemsAdder calls an event with the player set to null.
