### ISSUE TITLE
Possible incompatibility with FAWE

### ISSUE THREAD

**Issue by GrimPlayzs** [xenondevs/Nova#252]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 13.5, Paper version git-Paper-545 (MC: 1.19.4)

### Nova Addons and Versions

Vanilla Hammers, Jetpacks, Simple Upgrades, Logistics, and Machines all latest version.

### Expected behavior

I expect no errors to occur.

### Observed/Actual behavior

Fast Async World Edit shows an exception in chat and console when interacting or breaking blocks with any of the custom gear added by the Machines addon.

### Steps to reproduce

Install Nova with the Machines addon and Fast Async World Edit
Give yourself any of the Star gear or hammers
Interact or break any block.

### Full server log

https://gist.github.com/GrimPlayzs/3a10627584816d87a22a460896cc9501

### Errors

https://gist.github.com/GrimPlayzs/06d5d684584af68ad3b7f1ec55981294

**Comment by NichtStudioCode** [comment]
This cannot be fixed on our end.

**Comment by DevSrSouza** [comment]
Apparently there is also a problem with official WorldEdit in 1.14-RC1 server 1.20.1

```java
[14:32:25 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@24e196e7 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.WorldEdit.handleArmSwing(WorldEdit.java:633) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:122) ~[worldedit-bukkit-7.2.15.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-47]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-47]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:561) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:518) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:512) ~[paper-1.20.1.jar:git-Paper-47]
	at xyz.xenondevs.nova.world.block.logic.break.BlockBreaking.handleDestroyStart(BlockBreaking.kt:116) ~[Nova-0.14-RC.1.jar:?]
	at xyz.xenondevs.nova.world.block.logic.break.BlockBreaking.handlePlayerAction$lambda$1(BlockBreaking.kt:178) ~[Nova-0.14-RC.1.jar:?]
	at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTask$lambda$2(SchedulerUtils.kt:25) ~[Nova-0.14-RC.1.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-47]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-47]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Don't know how to make native xyz.xenondevs.nova.data.serialization.cbf.CBFCompoundTag
	at com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter.toNative(PaperweightAdapter.java:911) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter.toNative(PaperweightAdapter.java:878) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R1.PaperweightAdapter.adapt(PaperweightAdapter.java:599) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:529) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.bukkit.BukkitPlayer.getItemInHand(BukkitPlayer.java:82) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.extension.platform.PlayerProxy.getItemInHand(PlayerProxy.java:69) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:424) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.15.jar:7.2.15]
	... 25 more
```

**Comment by GrimPlayzs** [comment]
I already made an issue request on FAWE's Git Hub with no progress. 
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2261
