### ISSUE TITLE
Exceptions while ticking error then eventually locking up server. (quarry running)

### ISSUE THREAD

**Issue by xpbr2000** [xenondevs/Nova#270]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Paper version git-Paper-84 (MC: 1.20.1)  running through fork server manager on a local server in my personal network

### Nova Addons and Versions

nova 0.14.6, jetpacks 0.1.10, logistics 0.2.6, machines 0.4.3, simple upgrades 1.1, avnilla hammers 1.2

### Expected behavior

I expected the quarry to run with speed upgrades into a storage chest that sorts all items in a network of storage chests with filters. with all other machines and vanilla generators collecting to the same storage network.

### Observed/Actual behavior

-Start quarry
-items move through the storage system filtering and trashing items as needed
-exception while ticking error usually begin to appear on the server log
-after a undetermined amount of time passes server locks up and eventually kicks all players due to time out
-after waiting for the full thread dump the server attempts to shut down
-the server never shuts down completely. it hangs on "[Nova] [Machines] Disabling Machines [machines] v0.4.3"

### Steps to reproduce

1. run quarry at any speed or size 
2. (note i was also running a farm with the harvester and planter along with a sugar cane/bamboo/and iron generator all in different chunks)
3. wait undetermined amount of time.  
4. watch tick errors appear after a inconsistent amount of time
5. if running long enough it will lock up the server and time out the connections for all players and start thread dumping.
6. can be reproduced every time if quarry is ran long enough

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/12134713/latest.log)

### Errors

review log file.
Several of these in a row
[00:31:25] [Craft Scheduler Thread - 84 - Nova/ERROR]: [Nova] An exception occurred while ticking xyz.xenondevs.nova.machines.tileentity.world.Quarry(Material: xyz.xenondevs.nova.world.block.NovaTileEntityBlock@75db8565, Location: BlockPos(world=CraftWorld{name=world}, x=45, y=58, z=-253), UUID: dc732c0b-0c5b-4388-abeb-c08e3d618628)
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1625) ~[?:?]
	at xyz.xenondevs.nova.machines.tileentity.world.Quarry.updatePointer(Quarry.kt:722) ~[?:?]
	at xyz.xenondevs.nova.machines.tileentity.world.Quarry.updatePointer$default(Quarry.kt:356) ~[?:?]
	at xyz.xenondevs.nova.machines.tileentity.world.Quarry.handleAsyncTick(Quarry.kt:279) ~[?:?]
	at xyz.xenondevs.nova.tileentity.TileEntityManager$init$2$1.invoke(TileEntityManager.kt:49) ~[Nova-0.14.6.jar:?]
	at xyz.xenondevs.nova.tileentity.TileEntityManager$init$2$1.invoke(TileEntityManager.kt:49) ~[Nova-0.14.6.jar:?]
	at xyz.xenondevs.nova.tileentity.TileEntityManager.init$handleTick(TileEntityManager.kt:40) ~[Nova-0.14.6.jar:?]
	at xyz.xenondevs.nova.tileentity.TileEntityManager.init$lambda$5(TileEntityManager.kt:49) ~[Nova-0.14.6.jar:?]
	at xyz.xenondevs.nova.util.SchedulerUtilsKt.runAsyncTaskTimer$lambda$15(SchedulerUtils.kt:69) ~[Nova-0.14.6.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-84]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-84]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Additional context

originally witnessed with all the plugins, but during debug removed all other plugins and achieved the same result. 

I noticed that every other time the thread dump included quarry or something similar. This last test to pass the time I tested a bone meal generator with the harvester and it showed up in the thread dump. Not sure if this is a quarry issue or just a item storage/moving issue.

let me know what you need. I'll provide all I can.

**Comment by Akiranya** [comment]
It might be useful if you use `jstack` linux command to dump the stackframes of all the threads in the jvm, while the server is stuck.

Though I think the latest.log already contains the information about all the frames ...

**Comment by NichtStudioCode** [comment]
Please let me know whether this still happens with 0.14.7

**Comment by xpbr2000** [comment]
> 

Will do. Thank you.
