### ISSUE TITLE
Block loading slow burst error

### ISSUE THREAD

**Issue by mcprsx** [xenondevs/Nova#273]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova v0.14.10

### Nova Addons and Versions

Jetpacks-0.1.10.jar Logistics-0.2.6.jar Machines-0.4.3.jar Simple-Upgrades-1.1.jar Vanilla-Hammers-1.2.jar

### Observed/Actual behavior

When running the map, the wrong block in the background is loaded slowly

### Steps to reproduce

1. Running map
2. Slow loading of blocks
3. Backstage error

### Full server log

https://gist.githubusercontent.com/mcprsx/731c8574a5b3588444f4e9be207466ba/raw/4b5e299fec381193e347cabe92ed594d61a72701/gistfile1.txt

### Errors

[23:48:21] [Nova Chunk Searcher/ERROR]: [Nova] An error occurred while doing a chunk search
java.lang.ClassCastException: class net.minecraft.world.level.chunk.ChunkSection cannot be cast to class xyz.xenondevs.nova.transformer.patch.worldgen.chunksection.LevelChunkSectionWrapper (net.minecraft.world.level.chunk.ChunkSection and xyz.xenondevs.nova.transformer.patch.worldgen.chunksection.LevelChunkSectionWrapper are in unnamed module of loader java.net.URLClassLoader @66cd51c3)
	at xyz.xenondevs.nova.util.world.BlockStateSearcher.searchChunk(BlockStateSearcher.kt:41) ~[Nova-0.14.10.jar:?]
	at xyz.xenondevs.nova.world.block.backingstate.BackingStateManager.startChunkSearcher$lambda$7(BackingStateManager.kt:92) ~[Nova-0.14.10.jar:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]

**Comment by mcprsx** [comment]
It was later found that it conflicted with the BetterStructures plugin. After several attempts
