### ISSUE TITLE
NullPointerException when querying towny protection

### ISSUE THREAD

**Issue by Alzucard** [xenondevs/Nova#274]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Paper latest, Nova latest

### Nova Addons and Versions

Machines latest, Logistics latest, Addons latest

### Expected behavior

I expect no Error messages. They are really frequent.

### Observed/Actual behavior

It seems to work fine besides the hundreds of error messages.

### Steps to reproduce

1. Install Nova.

2. Install Addons

3. start using the addons

### Full server log

[latest(1)(1).log](https://github.com/xenondevs/Nova/files/12361740/latest.1.1.log)

### Errors

```java
[14:17:47] [Nova Protection Worker - 5/WARN]: [com.github.benmanes.caffeine.cache.BoundedLocalCache] Exception thrown during refresh
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
	at com.palmergames.bukkit.towny.object.PlayerCache.getBlockPermission(PlayerCache.java:136) ~[Towny-0.99.5.0.jar:?]
	at com.palmergames.bukkit.towny.object.PlayerCache.getCachePermission(PlayerCache.java:92) ~[Towny-0.99.5.0.jar:?]
	at com.palmergames.bukkit.towny.utils.PlayerCacheUtil.getCachePermission(PlayerCacheUtil.java:98) ~[Towny-0.99.5.0.jar:?]
	at xyz.xenondevs.nova.hook.impl.towny.TownyHook.hasPermission(TownyHook.kt:38) ~[Nova-0.14.10.jar:?]
	at xyz.xenondevs.nova.hook.impl.towny.TownyHook.canBreak(TownyHook.kt:20) ~[Nova-0.14.10.jar:?]
	at xyz.xenondevs.nova.api.protection.ProtectionIntegration.canBreak(ProtectionIntegration.java:43) ~[Nova-0.14.10.jar:?]
	at xyz.xenondevs.nova.integration.protection.ProtectionManager.init$lambda$11$lambda$10(ProtectionManager.kt:115) ~[Nova-0.14.10.jar:?]
	at xyz.xenondevs.nova.integration.protection.ProtectionManager.checkIntegrations(ProtectionManager.kt:247) ~[Nova-0.14.10.jar:?]
	at xyz.xenondevs.nova.integration.protection.ProtectionManager.checkProtection(ProtectionManager.kt:224) ~[Nova-0.14.10.jar:?]
	at xyz.xenondevs.nova.integration.protection.ProtectionManager.init$lambda$11(ProtectionManager.kt:115) ~[Nova-0.14.10.jar:?]
	at xyz.xenondevs.nova.integration.protection.ProtectionManager.init$lambda$12(ProtectionManager.kt:115) ~[Nova-0.14.10.jar:?]
	at com.github.benmanes.caffeine.cache.CacheLoader.reload(CacheLoader.java:169) ~[caffeine-3.1.6.jar:3.1.6]
	at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncReload$2(CacheLoader.java:196) ~[caffeine-3.1.6.jar:3.1.6]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
```

### Additional context

I dont really know what exactly causes it. Ingame.
We started using different blocks. Quarry, logistic item transfer, block placer and block breaker, quarry, creative power source. My guess is the creative power source atm. or the quary trying to break a block that isnt there.
Couldnt use Pastebin cause it was to much text so i simply uploaded the lates log file.

**Comment by Alzucard** [comment]
The plaacing of a querry gives us the Exception as far as we can tell.

**Comment by NichtStudioCode** [comment]
This looks more like a Towny issue to me

**Comment by Alzucard** [comment]
Interesting. Good point im gonna test that.
