### ISSUE TITLE
NullPointerException when generating chest loot

### ISSUE THREAD

**Issue by Madop67** [xenondevs/Nova#292]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.15-alpha3, Paper Build #226 (1.20.2)

### Nova Addons and Versions

Simple-Upgrades-1.2-RC.1, Machines-0.4.4-RC.1

### Observed/Actual behavior

Console returns an error when opening a chest with a modified loot table

### Steps to reproduce

1. teleport to any chest with a modified loot table (I used a desert pyramid)
2. open the chest

### Full server log

[loot_error.log](https://github.com/xenondevs/Nova/files/12889447/loot_error.log)

### Errors

```log
java.lang.NullPointerException: Cannot invoke "org.bukkit.loot.LootTable.getKey()" because the return value of "org.bukkit.event.world.LootGenerateEvent.getLootTable()" is null
	at xyz.xenondevs.nova.world.loot.LootGeneration.handleLootGenerationEvent(LootGeneration.kt:31) ~[Nova-0.15-alpha.3.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-226]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-226]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-226]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callLootGenerateEvent(CraftEventFactory.java:1960) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.world.level.storage.loot.LootTable.fillInventory(LootTable.java:171) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.world.level.storage.loot.LootTable.fill(LootTable.java:162) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.unpackLootTable(RandomizableContainerBlockEntity.java:85) ~[?:?]
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.createMenu(RandomizableContainerBlockEntity.java:165) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1564) ~[?:?]
	at net.minecraft.world.level.block.ChestBlock.use(ChestBlock.java:269) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1225) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:582) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1907) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1410) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-226]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by wordandahalf** [comment]
According to Paper's [documentation](https://jd.papermc.io/paper/1.20/org/bukkit/event/world/LootGenerateEvent.html#getLootTable()), `LootGenerateEvent#getLootTable` should never return `null`.

**Comment by wordandahalf** [comment]
Anyhow, I attempted to reproduce with a Nova addon that does not modify any loot tables and did not encounter the error.  I will attempt to reproduce with an addon that does modify a table.

**Comment by NichtStudioCode** [comment]
I cannot reproduce this on paper-223, and as @wordandahalf said, `LootGenerateEvent#getLootTable` is annotated with `@NotNull`, which would make it a Paper bug.
