### ISSUE TITLE
An exception occurred trying to initialize xyz/xenondevs/nova/item/enchantment/VanillaEnchantmentCategories

### ISSUE THREAD

**Issue by Day-OS** [xenondevs/Nova#299]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova v0.15-alpha.5, Java 18, git-Purpur-2083

### Nova Addons and Versions

None

### Observed/Actual behavior

Server instantly Crashes

### Steps to reproduce

Install Nova in a Purpur server

### Full server log

[02:39:17 INFO]: [Nova] Enabling Nova v0.15-alpha.5
[02:39:19 INFO]: [Nova] Extracting default config
[02:39:20 INFO]: [Nova] Registering packet handlers
[02:39:20 INFO]: [Nova] Loading Addons...
[02:39:20 INFO]: [Nova] Applying patches...
[02:39:26 ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/item/enchantment/VanillaEnchantmentCategories
java.lang.ExceptionInInitializerError: null
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:488) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:65) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.15-alpha.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(Unknown Source) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(Unknown Source) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / nova:enchantment]: ResourceKey[nova:enchantment / vane_enchantments:hell_bent]
        at net.minecraft.core.Registry.getOrThrow(Registry.java:103) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at xyz.xenondevs.nova.util.NMSUtilsKt.getOrThrow(NMSUtils.kt:379) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.item.enchantment.Enchantment$Companion.of(Enchantment.kt:87) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategory.<init>(EnchantmentCategory.kt:104) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.register(VanillaEnchantmentCategories.kt:30) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.<clinit>(VanillaEnchantmentCategories.kt:17) ~[Nova-0.15-alpha.5.jar:?]
        ... 18 more
[02:39:26 WARN]: [Nova] Shutting down the server...

**Comment by NichtStudioCode** [comment]
Missing server log.

**Comment by Day-OS** [comment]
Updated

**Comment by Day-OS** [comment]
Could this be reevaluated? I think it is not fair that it was completely ignored even after I included the information required.

I really want to develop with Nova, but I really can't run it in my production server.

**Comment by Day-OS** [comment]
Solved the issue! It was a incompatibility with Vane Enchantments.
