### ISSUE TITLE
[Bug] Jetpack bug in when connecting

### ISSUE THREAD

**Issue by Sheikins** [xenondevs/Nova#30]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Plugin Version and Server Software

Nova: 0.5.1 Version: 1.17.1

### Expected behavior

Bug in the console

### Observed/Actual behavior

The jetpack bar is showing but I don't have a jetpack on me.

### Steps to reproduce

I do not understand when this happens

### Errors

[22:00:13] [Server thread/WARN]: [Nova] Task #1610 for Nova v0.5.1 generated an exception
java.lang.NullPointerException: null
        at xyz.xenondevs.nova.player.ability.JetpackFlyAbility.getJetpackItem(JetpackFlyAbility.kt:26) ~[?:?]
        at xyz.xenondevs.nova.player.ability.JetpackFlyAbility.handleTick(JetpackFlyAbility.kt:44) ~[?:?]
        at xyz.xenondevs.nova.player.ability.AbilityManager$init$2.invoke(AbilityManager.kt:33) ~[?:?]
        at xyz.xenondevs.nova.player.ability.AbilityManager$init$2.invoke(AbilityManager.kt:32) ~[?:?]
        at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTaskTimer$lambda-2(SchedulerUtils.kt:13) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at java.lang.Thread.run(Thread.java:831) [?:?]

[22:05:14] [Server thread/ERROR]: Could not pass event ArmorEquipEvent to Nova v0.5.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at xyz.xenondevs.nova.player.equipment.ArmorEquipListener.handleInventoryClick(ArmorEquipListener.kt:109) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2427) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: Tried to register an attachment under a key which is already occupied.
        at xyz.xenondevs.nova.player.attachment.AttachmentManager.registerAttachment(AttachmentManager.kt:38) ~[?:?]
        at xyz.xenondevs.nova.player.attachment.Attachment.<init>(Attachment.kt:47) ~[?:?]
        at xyz.xenondevs.nova.item.impl.JetpackItem.handleEquip(JetpackItem.kt:23) ~[?:?]
        at xyz.xenondevs.nova.item.ItemManager.handleEquip(ItemManager.kt:39) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        ... 27 more

**Comment by NichtStudioCode** [comment]
Invalid server version
Expected / Observer behavior fields are not filled out correctly
No steps this issue reproduce this issue
Not using pastebin for stacktraces
