### ISSUE TITLE
STDERR and LuckPerms hook errors

### ISSUE THREAD

**Issue by BiddinWar** [xenondevs/Nova#303]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.
- [X] I am using an official build of Nova.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova-0.15-alpha.5, PaperMC: paper-1.20.2-248, MC 1.20.2

### Nova Addons and Versions

None

### Expected behavior

Following setup-guide and not encountering errors.

### Observed/Actual behavior

Encountered two error messages in Server console.
First one - byte-buddy-agent?
Second one - Related to LuckPerms hook failing?

### Steps to reproduce

1. Downloaded and placed Nova-0.15-alpha.5 in plugins folder
2. Started server to have Nova generated appropriated folders etc for Nova Addons
3. Observed errors
4. Closed server

### Full server log

[latest.log](https://github.com/xenondevs/Nova/files/13257135/latest.log)

### Errors

```log
[16:57:47 ERROR]: [STDERR] [sun.instrument.InstrumentationImpl] WARNING: A Java agent has been loaded dynamically (H:\Minecraft Server\libraries\net\bytebuddy\byte-buddy-agent\1.12.20\byte-buddy-agent-1.12.20.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release

[16:58:50 ERROR]: [Nova] Failed to load hook xyz/xenondevs/nova/hook/impl/luckperms/LuckPermsHook
java.lang.NoClassDefFoundError: net/luckperms/api/LuckPermsProvider
        at xyz.xenondevs.nova.hook.impl.luckperms.LuckPermsHook.<clinit>(LuckPermsHook.kt:16) ~[Nova-0.15-alpha.5.jar:?]        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.lang.Class.forName(Class.java:412) ~[?:?]
        at xyz.xenondevs.nova.integration.HooksLoader.loadHook(HooksLoader.kt:69) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.integration.HooksLoader.loadHooks(HooksLoader.kt:40) ~[Nova-0.15-alpha.5.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.9.10.jar:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.9.10.jar:1.9.10-release-459]
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.9.10.jar:1.9.10-release-459]
        at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:75) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.initialize.Initializer.initPostWorld$lambda$10$lambda$8$lambda$7(Initializer.kt:167) ~[Nova-0.15-alpha.5.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPermsProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at xyz.xenondevs.nova.loader.NovaClassLoader.loadClass(NovaClassLoader.java:48) ~[Nova-0.15-alpha.5.jar:?]
        at xyz.xenondevs.nova.loader.NovaClassLoader.loadClass(NovaClassLoader.java:29) ~[Nova-0.15-alpha.5.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 18 more
```

**Comment by NichtStudioCode** [comment]
You can ignore the warning about the dynamic java agent or run the server with ``-XX:+EnableDynamicAgentLoading`` as suggested in the warning.
