### ISSUE TITLE
Resource Pack obfuscator throws "java.lang.UnsupportedOperationException: Unsupported source type: paletted_permutations"

### ISSUE THREAD

**Issue by AwesomeKalin** [xenondevs/Nova#322]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.16-alpha2 Pufferfish: Build 41

### Nova Addons and Versions

None

### Expected behavior

Shouldn't crash the server

### Observed/Actual behavior

Server crashes

### Steps to reproduce

1. Enable resource pack obfuscation
2. Start the server

### Server log

https://mclo.gs/C4l79C1

### Errors

```log
[Nova Initializer - 12/ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/data/resources/ResourceGeneration$PostWorld
java.lang.UnsupportedOperationException: Unsupported source type: paletted_permutations
	at xyz.xenondevs.resourcepackobfuscator.obfuscation.atlas.AtlasSource$Companion.fromJson(AtlasSource.kt:24) ~[resource-pack-obfuscator-0.4.1.jar:?]
	at xyz.xenondevs.resourcepackobfuscator.obfuscation.atlas.AtlasSources.lambda-1$loadAtlas(AtlasSources.kt:31) ~[resource-pack-obfuscator-0.4.1.jar:?]
	at xyz.xenondevs.resourcepackobfuscator.obfuscation.atlas.AtlasSources.<init>(AtlasSources.kt:35) ~[resource-pack-obfuscator-0.4.1.jar:?]
	at xyz.xenondevs.resourcepackobfuscator.obfuscation.Renamer.<init>(Renamer.kt:32) ~[resource-pack-obfuscator-0.4.1.jar:?]
	at xyz.xenondevs.resourcepackobfuscator.ResourcePackObfuscator.packZip(ResourcePackObfuscator.kt:51) ~[resource-pack-obfuscator-0.4.1.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.createZip(ResourcePackBuilder.kt:307) ~[Nova-0.16-alpha.2.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.buildPackPostWorld$nova(ResourcePackBuilder.kt:246) ~[Nova-0.16-alpha.2.jar:?]
	at xyz.xenondevs.nova.data.resources.ResourceGeneration$PostWorld.init(ResourceGeneration.kt:66) ~[Nova-0.16-alpha.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:75) ~[Nova-0.16-alpha.2.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.initPostWorld$lambda$10$lambda$8$lambda$7(Initializer.kt:167) ~[Nova-0.16-alpha.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Additional context

Using ViaVersion, ViaBackwards, Terra and Multiverse

**Comment by AwesomeKalin** [comment]
Offline mode is on since the server is behind Velocity
