### ISSUE TITLE
Compatibility error with items adder

### ISSUE THREAD

**Issue by RAPHAEL599** [xenondevs/Nova#327]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.16-alpha.2 Current: git-Purpur-2139 (MC: 1.20.4)* * You are running the latest version

### Nova Addons and Versions

Logistics-0.2.8-RC.1 Machines-0.4.5-RC.1 Simple-Upgrades-1.3-RC.1

### Expected behavior

The plugin takes the texture from the items adder and combines it with Nova's own

### Observed/Actual behavior

Error when combining textures

### Steps to reproduce

1. Have the items adder that uses font texture
2. Have Nova get the texture from the items adder to create its own
3. ERRO

### Server log

[latest (2).log](https://github.com/xenondevs/Nova/files/14230708/latest.2.log)

### Errors

```log
[19:25:27 ERROR]: [Nova] An exception occurred running a task
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
        at xyz.xenondevs.nova.data.resources.builder.task.PackFunction.run(PackTask.kt:119) ~[Nova-0.16-alpha.2.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.runPackFunction(ResourcePackBuilder.kt:314) ~[Nova-0.16-alpha.2.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.buildPackPreWorld$nova(ResourcePackBuilder.kt:228) ~[Nova-0.16-alpha.2.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.buildPackCompletely$nova(ResourcePackBuilder.kt:185) ~[Nova-0.16-alpha.2.jar:?]
        at xyz.xenondevs.nova.data.resources.ResourceGeneration.createResourcePack$nova(ResourceGeneration.kt:96) ~[Nova-0.16-alpha.2.jar:?]
        at xyz.xenondevs.nova.command.impl.NovaCommand.createResourcePack$lambda$17(NovaCommand.kt:191) ~[Nova-0.16-alpha.2.jar:?]
        at xyz.xenondevs.nova.util.AsyncExecutor.run$lambda$0(SchedulerUtils.kt:91) ~[Nova-0.16-alpha.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Font _iainternal:gui does not exist or is not loaded in FontContent
        at xyz.xenondevs.nova.data.resources.builder.task.font.MovedFontContent.getBitmapFont(MovedFontContent.kt:88) ~[Nova-0.16-alpha.2.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.task.font.MovedFontContent.write(MovedFontContent.kt:65) ~[Nova-0.16-alpha.2.jar:?]
        ... 20 more
```

**Comment by RAPHAEL599** [comment]
A suggestion to resolve this would be to add the already made configuration files containing the Nova assets to ItemsAdder (Just like slime fun did)

**Comment by ByteZ1337** [comment]
Post your config

**Comment by RAPHAEL599** [comment]
From Nova or Items Adder?

**Comment by ByteZ1337** [comment]
Both would be great

**Comment by RAPHAEL599** [comment]
[ItemsAdder.tar.gz](https://github.com/xenondevs/Nova/files/14230811/ItemsAdder.tar.gz)
[Nova.tar.gz](https://github.com/xenondevs/Nova/files/14230812/Nova.tar.gz)

I know the upload is wrong, I would configure it after I managed to merge the texts

**Comment by RAPHAEL599** [comment]
Any solution so I can install the plugin today?

**Comment by ByteZ1337** [comment]
Not today. I'll test your setup tomorrow.

**Comment by RAPHAEL599** [comment]
![image](https://github.com/xenondevs/Nova/assets/73084300/01e11f73-81d8-493e-9b38-007f30a3f6b3)
When I use it with items adder it looks like this

**Comment by RAPHAEL599** [comment]
Can I report another completely different bug here or should I open a topic?

**Comment by NichtStudioCode** [comment]
> Can I report another completely different bug here or should I open a topic?

Create a separate issue.
