### ISSUE TITLE
 Items Adder support still doesn't work

### ISSUE THREAD

**Issue by RAPHAEL599** [xenondevs/Nova#329]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.16-alpha.3 Current: git-Purpur-2139 (MC: 1.20.4)* * You are running the latest version

### Nova Addons and Versions

Logistics-0.2.8-RC.1 Machines-0.4.5-RC.1 Simple-Upgrades-1.3-RC.1

### Expected behavior

The plugin takes the texture from the items adder and combines it with Nova's own

### Observed/Actual behavior

Error when combining textures

### Steps to reproduce

[https://youtu.be/1cSPdfKI-jc](https://youtu.be/1cSPdfKI-jc)

### Server log

[latest (4).log](https://github.com/xenondevs/Nova/files/14232802/latest.4.log)

### Errors

```log
[11:58:23 ERROR]: [Nova] An exception occurred running a task
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
        at xyz.xenondevs.nova.data.resources.builder.task.PackFunction.run(PackTask.kt:119) ~[Nova-0.16-alpha.3.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.runPackFunction(ResourcePackBuilder.kt:314) ~[Nova-0.16-alpha.3.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.buildPackPreWorld$nova(ResourcePackBuilder.kt:228) ~[Nova-0.16-alpha.3.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.buildPackCompletely$nova(ResourcePackBuilder.kt:185) ~[Nova-0.16-alpha.3.jar:?]
        at xyz.xenondevs.nova.data.resources.ResourceGeneration.createResourcePack$nova(ResourceGeneration.kt:96) ~[Nova-0.16-alpha.3.jar:?]
        at xyz.xenondevs.nova.command.impl.NovaCommand.createResourcePack$lambda$17(NovaCommand.kt:191) ~[Nova-0.16-alpha.3.jar:?]
        at xyz.xenondevs.nova.util.AsyncExecutor.run$lambda$0(SchedulerUtils.kt:91) ~[Nova-0.16-alpha.3.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.nio.file.FileAlreadyExistsException: /pack/assets/machines/sounds.json
        at java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:119) ~[?:?]
        at java.nio.file.Files.copy(Files.java:1308) ~[?:?]
        at xyz.xenondevs.nova.data.resources.builder.task.ExtractTask.extractAssetPack(ExtractTask.kt:97) ~[Nova-0.16-alpha.3.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.task.ExtractTask.extractAssetPacks(ExtractTask.kt:62) ~[Nova-0.16-alpha.3.jar:?]
        at xyz.xenondevs.nova.data.resources.builder.task.ExtractTask.extractAll(ExtractTask.kt:26) ~[Nova-0.16-alpha.3.jar:?]
        ... 20 more
```

### Additional context

[ItemsAdder.tar.gz](https://github.com/xenondevs/Nova/files/14232804/ItemsAdder.tar.gz)
[NovaConfig.tar.gz](https://github.com/xenondevs/Nova/files/14232806/NovaConfig.tar.gz)

**Comment by NichtStudioCode** [comment]
Please make sure to follow the ItemsAdder configuration changes outlined [here](https://docs.xenondevs.xyz/nova/admin/compatibility/itemsadder/).

**Comment by RAPHAEL599** [comment]
I tried again to disable itemsadder protections and it still didn't work

**Comment by RAPHAEL599** [comment]
Any news?

**Comment by ByteZ1337** [comment]
Did you also regenerate the pack after disabling protections?

**Comment by RAPHAEL599** [comment]
Yes

**Comment by RAPHAEL599** [comment]
In fact, I think I'll try manual merge and then use items adder to load the texture

**Comment by RAPHAEL599** [comment]
The real problem that I noticed between the textures is the font files, it seems that nova cannot combine the 2 and causes an error

**Comment by RAPHAEL599** [comment]
The manual merge worked
![image](https://github.com/xenondevs/Nova/assets/73084300/87bc2aa7-8aee-4340-ad27-55a77288e527)
![image](https://github.com/xenondevs/Nova/assets/73084300/476b7b34-959a-4838-be58-6e7189eb371a)
![image](https://github.com/xenondevs/Nova/assets/73084300/270c1680-544e-44ed-aa7f-7e70557affd1)

**Comment by RAPHAEL599** [comment]
Do you have any plans to fix this problem?

**Comment by NichtStudioCode** [comment]
> The real problem that I noticed between the textures is the font files, it seems that nova cannot combine the 2 and causes an error

Not sure what you mean, sounds.json is not a font file?

I'd also need the newly generated ItemsAdder resource pack after the requested changes to the ItemsAdder config.

**Comment by RAPHAEL599** [comment]
What files do you need me to send you?

**Comment by NichtStudioCode** [comment]
> the newly generated ItemsAdder resource pack

**Comment by RAPHAEL599** [comment]
[generated (8).zip](https://github.com/xenondevs/Nova/files/14302090/generated.8.zip)
Here it is

**Comment by RAPHAEL599** [comment]
If you want to speed up support I can call via discord (raphael599)

**Comment by RAPHAEL599** [comment]
Do you have any solution to automate the joining of font images?
