### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by mrdeniska1234** [xenondevs/Nova#330]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.16 alpha3, purpur 1.20.4 b2141

### Nova Addons and Versions

machines v0.4.5-RC.2 Jetpacks v0.1.12-RC.1 Simple-Upgrades v1.3-RC.1 Logistics v0.2.8-RC.1

### Observed/Actual behavior

Server not start

### Steps to reproduce

1. Start server with bat

### Server log

[13:59:44] [Server thread/INFO]: [Nova] Extracting configs
[13:59:46] [Server thread/INFO]: [Nova] Initializing Addons...
[13:59:46] [Server thread/INFO]: [Nova] [Jetpacks] Initializing Jetpacks [jetpacks] v0.1.12-RC.1
[13:59:46] [Server thread/INFO]: [Nova] [Simple-Upgrades] Initializing Simple-Upgrades [simple_upgrades] v1.3-RC.1
[13:59:46] [Server thread/INFO]: [Nova] [Logistics] Initializing Logistics [logistics] v0.2.8-RC.1
[13:59:46] [Server thread/INFO]: [Nova] [Machines] Initializing Machines [machines] v0.4.5-RC.2
[13:59:48] [Server thread/INFO]: [Nova] Building resource pack
[13:59:49] [Server thread/INFO]: [Nova] Tasks (18):
[13:59:49] [Server thread/INFO]: [Nova]   PRE_WORLD (13):
[13:59:49] [Server thread/INFO]: [Nova]     ExtractTask#extractAll
[13:59:49] [Server thread/INFO]: [Nova]     MaterialContent#write
[13:59:49] [Server thread/INFO]: [Nova]     ArmorContent#write
[13:59:49] [Server thread/INFO]: [Nova]     GuiContent#write
[13:59:49] [Server thread/INFO]: [Nova]     LanguageContent#loadLangFiles
[13:59:49] [Server thread/INFO]: [Nova]     TextureIconContent#write
[13:59:49] [Server thread/INFO]: [Nova]     AtlasContent#write
[13:59:49] [Server thread/INFO]: [Nova]     SoundOverrides#write
[13:59:49] [Server thread/INFO]: [Nova]     FontContent#discoverAllFonts
[13:59:49] [Server thread/INFO]: [Nova]     BarOverlayTask#requestMovedFonts
[13:59:49] [Server thread/INFO]: [Nova]     MoveCharactersContent#write
[13:59:49] [Server thread/INFO]: [Nova]     EnchantmentContent#createBackgroundChars
[13:59:49] [Server thread/INFO]: [Nova]     MovedFontContent#write
[13:59:49] [Server thread/INFO]: [Nova]   POST_WORLD (5):
[13:59:49] [Server thread/INFO]: [Nova]     WailaContent#write
[13:59:49] [Server thread/INFO]: [Nova]     CharSizeCalculator#calculateCharSizes
[13:59:49] [Server thread/INFO]: [Nova]     EnchantmentContent#write
[13:59:49] [Server thread/INFO]: [Nova]     LanguageContent#write
[13:59:49] [Server thread/INFO]: [Nova]     FontContent#write
[13:59:49] [Server thread/INFO]: [Nova] Asset packs (5): logistics, jetpacks, machines, simple_upgrades, nova
[13:59:51] [Server thread/INFO]: [Nova] Adding base pack /base_packs/pack-ljPML
[13:59:52] [Server thread/INFO]: [Nova] Running pre-world pack tasks
[13:59:52] [Server thread/ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/data/resources/ResourceGeneration$PreWorld
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at xyz.xenondevs.nova.data.resources.builder.task.PackFunction.run(PackTask.kt:119) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.runPackFunction(ResourcePackBuilder.kt:314) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.ResourcePackBuilder.buildPackPreWorld$nova(ResourcePackBuilder.kt:228) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.data.resources.ResourceGeneration$PreWorld.init(ResourceGeneration.kt:48) ~[Nova-0.16-alpha.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.9.20.jar:1.9.255-SNAPSHOT]
	at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:75) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16-alpha.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2119]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2119]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2119]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2119]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.4.jar:git-Purpur-2119]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2119]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2119]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.nio.file.FileAlreadyExistsException: /pack/assets/machines/sounds.json
	at java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:136) ~[?:?]
	at java.nio.file.Files.copy(Files.java:1307) ~[?:?]
	at xyz.xenondevs.nova.data.resources.builder.task.ExtractTask.extractAssetPack(ExtractTask.kt:97) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.task.ExtractTask.extractAssetPacks(ExtractTask.kt:62) ~[Nova-0.16-alpha.3.jar:?]
	at xyz.xenondevs.nova.data.resources.builder.task.ExtractTask.extractAll(ExtractTask.kt:26) ~[Nova-0.16-alpha.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... 28 more
[13:59:52] [Server thread/WARN]: [Nova] Shutting down the server...

**Comment by NichtStudioCode** [comment]
Incomplete server log
