### ISSUE TITLE
Plugin tweakin causes an exception in Nova

### ISSUE THREAD

**Issue by SiriusArtistry** [xenondevs/Nova#341]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.16-alpha.4, Paper: git-Paper-448 (MC: 1.20.4)

### Nova Addons and Versions

Logistics-0.2.8-RC.1, Machines-0.4.5-RC.3, Simple-Upgrades-1.3-RC.1, Vanilla-Hammers-1.4-RC.1

### Expected behavior

Nova loads addons and applies patches alongside plugins ExcellentEnchants, NexEngine 2.2.12, ProtocolLib 5.2.0-SNAPSHOT-679, Tweakin, Vane Core, Vane Enchantments, and WolfyUtilities

### Observed/Actual behavior

Exception when trying to initialize vanilla enchantment categories when plugin Tweakin is enabled alongside listed plugins.

### Steps to reproduce

1. Place Nova-0.16-alpha.4.jar, ExcellentEnchants-3.6.5.jar, NexEngine.jar, ProtocolLib.jar, Tweakin-7.0.3.jar, vane-core-1.14.0.jar, vane-enchantments-1.14.0.jar, and wolfyutils-spigot-4.16.15.1.jar in 'plugins' folder
2. Place Logistics-0.2.8-RC.1.jar, Machines-0.4.5-RC.3.jar, Simple-Upgrades-1.3-RC.1.jar, and Vanilla-Hammers-1.4-RC.1 in 'plugins/Nova/addons' folder
3. Run server

### Server log

[latest.log](https://github.com/xenondevs/Nova/files/14783897/latest.log)

### Errors

```log
[23:58:52] [Server thread/INFO]: [Nova] Enabling Nova v0.16-alpha.4
[23:58:53] [Server thread/INFO]: [Nova] Extracting default config
[23:58:54] [Server thread/INFO]: [Nova] Registering packet handlers
[23:58:54] [Server thread/INFO]: [Nova] Loading Addons...
[23:58:54] [Server thread/INFO]: [Nova] [Logistics] Loaded Logistics [logistics] v0.2.8-RC.1
[23:58:54] [Server thread/INFO]: [Nova] [Machines] Loaded Machines [machines] v0.4.5-RC.3
[23:58:54] [Server thread/INFO]: [Nova] [Simple-Upgrades] Loaded Simple-Upgrades [simple_upgrades] v1.3-RC.1
[23:58:54] [Server thread/INFO]: [Nova] [Vanilla-Hammers] Loaded Vanilla-Hammers [vanilla_hammers] v1.4-RC.1
[23:58:54] [Server thread/INFO]: [Nova] Applying patches...
[23:58:58] [Server thread/ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/item/enchantment/VanillaEnchantmentCategories
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.lang.Class.forName(Class.java:474) ~[?:?]
	at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:65) ~[Nova-0.16-alpha.4.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[Nova-0.16-alpha.4.jar:?]
	at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[Nova-0.16-alpha.4.jar:?]
	at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[Nova-0.16-alpha.4.jar:?]
	at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16-alpha.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-448]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[paper-1.20.4.jar:git-Paper-448]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[paper-1.20.4.jar:git-Paper-448]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[paper-1.20.4.jar:git-Paper-448]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-448]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / nova:enchantment]: ResourceKey[nova:enchantment / minecraft:elemental_protection]
	at net.minecraft.core.Registry.getOrThrow(Registry.java:103) ~[paper-1.20.4.jar:git-Paper-448]
	at xyz.xenondevs.nova.util.NMSUtilsKt.getOrThrow(NMSUtils.kt:379) ~[Nova-0.16-alpha.4.jar:?]
	at xyz.xenondevs.nova.item.enchantment.Enchantment$Companion.of(Enchantment.kt:88) ~[Nova-0.16-alpha.4.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategory.<init>(EnchantmentCategory.kt:107) ~[Nova-0.16-alpha.4.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.register(VanillaEnchantmentCategories.kt:30) ~[Nova-0.16-alpha.4.jar:?]
	at xyz.xenondevs.nova.item.enchantment.VanillaEnchantmentCategories.<clinit>(VanillaEnchantmentCategories.kt:13) ~[Nova-0.16-alpha.4.jar:?]
	... 18 more
[23:58:58] [Server thread/WARN]: [Nova] Shutting down the server...
[23:58:58] [Server thread/INFO]: Preparing level "lobby"
```

### Additional context

All of the listed plugins with the exception of Tweakin work fine, but when Tweakin is enabled, nova throws an exception.

**Comment by ByteZ1337** [comment]
ExcellentEnchants registers custom enchantments under the `minecraft` namespace, which is unsupported. As the namespace name `minecraft` suggests, this namespace should only be used for enchantments found in vanilla minecraft.
