### ISSUE TITLE
Error and crash

### ISSUE THREAD

**Issue by euj3ne** [xenondevs/Nova#357]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.16-RC.1

### Nova Addons and Versions

-

### Observed/Actual behavior

-

### Steps to reproduce

Upload and start.

### Server log

[2024-04-02-5.log](https://github.com/xenondevs/Nova/files/14837796/2024-04-02-5.log)

### Errors

```log
[Nova] An exception occurred trying to initialize xyz/xenondevs/nova/transformer/Patcher
xyz.xenondevs.nova.transformer.PatcherException: 
    JDK: 17.0.10 by Eclipse Adoptium
    JVM: OpenJDK 64-Bit Server VM, 17.0.10+7 by Eclipse Adoptium
    Operating system: Linux, amd64
    Startup parameters: [-Xms128M, -XX:MaxRAMPercentage=95.0, -Dterminal.jline=false, -Dterminal.ansi=true]
        at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:86) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[?:?]
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[?:?]
        at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:75) ~[?:?]
        at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[?:?]
        at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[?:?]
        at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[?:?]
        at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16-RC.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[plazma-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1153) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[plazma-1.20.4.jar:git-Plazma-"e4ca876"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at xyz.xenondevs.nova.transformer.patch.item.EnchantmentPatches.<init>(EnchantmentPatches.kt:59) ~[?:?]
        at xyz.xenondevs.nova.transformer.patch.item.EnchantmentPatches.<clinit>(EnchantmentPatches.kt) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.transformers_delegate$lambda$0(Patcher.kt:62) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.getTransformers(Patcher.kt:60) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.runTransformers(Patcher.kt:122) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:82) ~[?:?]
        ... 22 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.inventory.ContainerEnchantTable.lambda$slotsChanged$0(net.minecraft.world.item.ItemStack,net.minecraft.world.level.World,net.minecraft.core.BlockPosition)
        at java.lang.Class.getDeclaredMethod(Class.java:2675) ~[?:?]
        at xyz.xenondevs.nova.util.reflection.ReflectionUtils.getMethod(ReflectionUtils.kt:63) ~[?:?]
        at xyz.xenondevs.nova.util.reflection.ReflectionUtils.getMethod(ReflectionUtils.kt:54) ~[?:?]
        at xyz.xenondevs.nova.transformer.patch.item.EnchantmentPatchesKt.<clinit>(EnchantmentPatches.kt:21) ~[?:?]
        at xyz.xenondevs.nova.transformer.patch.item.EnchantmentPatches.<init>(EnchantmentPatches.kt:59) ~[?:?]
        at xyz.xenondevs.nova.transformer.patch.item.EnchantmentPatches.<clinit>(EnchantmentPatches.kt) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.transformers_delegate$lambda$0(Patcher.kt:62) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.getTransformers(Patcher.kt:60) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.runTransformers(Patcher.kt:122) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:82) ~[?:?]
        ... 22 more
```

**Comment by NichtStudioCode** [comment]
Unsupported server software, please actually read the agreements

**Comment by euj3ne** [comment]
So it is written that this version supports 1.20.4 purpur.. :(

**Comment by NichtStudioCode** [comment]
You're not using purpur

**Comment by euj3ne** [comment]
plazma is a fork of purpur, isn't it?

**Comment by NichtStudioCode** [comment]
Plazma is not a supported server software, regardless of what it is forked from (which is Paper according to GitHub).
