### ISSUE TITLE
[15:18:46 ERROR]: Error occurred while enabling Nova v0.16 (Is it up to date?)

### ISSUE THREAD

**Issue by redstone5341r** [xenondevs/Nova#378]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: v0.16, Paper: 1.20.4-493

### Nova Addons and Versions

Logistics, Machines, Jetpacks

### Expected behavior

plugin to work

### Observed/Actual behavior

Nova disabled and some eror mesage

### Steps to reproduce

1, Place the plugin jar into /plugins folder
2, run the server
3, stop the server, move the addons into the addons folder
4, run again, then this shows up

### Server log

[latest.log](https://github.com/xenondevs/Nova/files/15065884/latest.log)

### Errors

```log
[16:26:16 ERROR]: Error occurred while enabling Nova v0.16 (Is it up to date?)
java.lang.RuntimeException: java.lang.IllegalStateException: zip file closed
	at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:26) ~[Nova-0.16.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-493]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-493]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-493]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-493]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-493]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-493]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-493]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:840) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:339) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:517) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:472) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.lookupClass(SimpleListPluginClassLoaderGroup.java:46) ~[paper-1.20.4.jar:git-Paper-493]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.20.4.jar:git-Paper-493]
	at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.20.4.jar:git-Paper-493]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:136) ~[paper-1.20.4.jar:git-Paper-493]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.4.jar:git-Paper-493]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at xyz.xenondevs.nova.loader.NovaClassLoader.tryLoadClass(NovaClassLoader.java:55) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.loader.NovaClassLoader.loadClass(NovaClassLoader.java:39) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.loader.NovaClassLoader.loadClass(NovaClassLoader.java:22) ~[Nova-0.16.jar:?]
	at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:21) ~[Nova-0.16.jar:?]
	... 10 more
[16:26:16 INFO]: [Nova] Disabling Nova v0.16
```

**Comment by LoAndEvolve** [comment]
I'm having this error as well only it started after a specific person joined the server, Nova disabled all recipes and then all machines and items returned to mushrooms and shulker shells.

**Comment by NichtStudioCode** [comment]
> This issue is about a specific plugin incompatibility.

And what plugin would that be?
