### ISSUE TITLE
[Bug] Jetpacks causing console spam, chunks not loading in Nova areas

### ISSUE THREAD

**Issue by SolarCiv** [xenondevs/Nova#38]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Plugin Version and Server Software

git-Paper-327 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8575248)

### Expected behavior

Being able to walk in chunks with Nova-related technology.
Having a console without spam.

### Observed/Actual behavior

Chunks not loading with Nova technology in them, Nova technology is spinning, the rest of the chunks around it aren't loading. Console being constantly spammed with Nova-related error messages.

### Steps to reproduce

1. Install the plugin, works fine.
2. Go to sleep.
3. Wake up and find the server console spammed with error messages, and chunks not loading with Nova technology.

### Errors

```
14.10 10:05:32 [Server] WARN Task #893 for Nova v0.5.4 generated an exception
14.10 10:05:32 [Server] INFO java.lang.NullPointerException: null
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.player.ability.JetpackFlyAbility.getJetpackItem(JetpackFlyAbility.kt:26) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.player.ability.JetpackFlyAbility.handleTick(JetpackFlyAbility.kt:44) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.player.ability.AbilityManager$init$2.invoke(AbilityManager.kt:33) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.player.ability.AbilityManager$init$2.invoke(AbilityManager.kt:32) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTaskTimer$lambda-2(SchedulerUtils.kt:13) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
14.10 10:05:32 [Server] WARN Task #893 for Nova v0.5.4 generated an exception
14.10 10:05:32 [Server] INFO java.lang.NullPointerException: null
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.player.ability.JetpackFlyAbility.getJetpackItem(JetpackFlyAbility.kt:26) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.player.ability.JetpackFlyAbility.handleTick(JetpackFlyAbility.kt:44) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.player.ability.AbilityManager$init$2.invoke(AbilityManager.kt:33) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.player.ability.AbilityManager$init$2.invoke(AbilityManager.kt:32) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTaskTimer$lambda-2(SchedulerUtils.kt:13) ~[Nova-0.5.4.jar:?]
14.10 10:05:32 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-327]
14.10 10:05:32 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### Additional context

We installed the plugin last night, seemed to be working fine. Woke up today, seen that the server had crashed and restarted itself, console is being spammed with the error message.

**Comment by SolarCiv** [comment]
![image](https://user-images.githubusercontent.com/91644728/137329670-502424f3-d136-4864-9c56-c7bbda5ce09e.png)
