### ISSUE TITLE
Nova spamming console

### ISSUE THREAD

**Issue by TerslenK** [xenondevs/Nova#392]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.16.1 / Latest Paper for 1.20.4

### Nova Addons and Versions

Logistic 0.2.8 / Machines 0.4.5 / Simple Upgrades 1.3

### Expected behavior

not spamming console

### Observed/Actual behavior

spamming console

### Steps to reproduce

have these plugins:
- BetterStructures
- Nova
- FastAsyncWorldEdit
- EliteMobs
- WorldGuard
- And some other plugins that arent affecting chunk loading( list is in additional content) 

### Server log

https://mclo.gs/oGNx0P3

### Errors

```log
[17:19:07] [Attach Listener/ERROR]: [STDERR] [sun.instrument.InstrumentationImpl] WARNING: A Java agent has been loaded dynamically (/home/********/libraries/net/bytebuddy/byte-buddy-agent/1.12.20/byte-buddy-agent-1.12.20.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
--------------------------------------------------------------------------------------------------------
[18:06:56] [Nova Chunk Searcher/ERROR]: [Nova] An error occurred while doing a chunk search
java.lang.ClassCastException: class net.minecraft.world.level.chunk.ChunkSection cannot be cast to class xyz.xenondevs.nova.transformer.patch.worldgen.chunksection.LevelChunkSectionWrapper (net.minecraft.world.level.chunk.ChunkSection and xyz.xenondevs.nova.transformer.patch.worldgen.chunksection.LevelChunkSectionWrapper are in unnamed module of loader java.net.URLClassLoader @41cf53f9)
	at xyz.xenondevs.nova.util.world.BlockStateSearcher.searchChunk(BlockStateSearcher.kt:41) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.world.block.backingstate.BackingStateManager.startChunkSearcher$lambda$7(BackingStateManager.kt:92) ~[Nova-0.16.1.jar:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) ~[kotlin-stdlib-1.9.23.jar:1.9.23-release-779]
[18:06:56] [Nova Chunk Searcher/ERROR]: [Nova] An error occurred while doing a chunk search
java.lang.ClassCastException: class net.minecraft.world.level.chunk.ChunkSection cannot be cast to class xyz.xenondevs.nova.transformer.patch.worldgen.chunksection.LevelChunkSectionWrapper (net.minecraft.world.level.chunk.ChunkSection and xyz.xenondevs.nova.transformer.patch.worldgen.chunksection.LevelChunkSectionWrapper are in unnamed module of loader java.net.URLClassLoader @41cf53f9)
	at xyz.xenondevs.nova.util.world.BlockStateSearcher.searchChunk(BlockStateSearcher.kt:41) ~[Nova-0.16.1.jar:?]
	at xyz.xenondevs.nova.world.block.backingstate.BackingStateManager.startChunkSearcher$lambda$7(BackingStateManager.kt:92) ~[Nova-0.16.1.jar:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) ~[kotlin-stdlib-1.9.23.jar:1.9.23-release-779]
```

### Additional context

![image](https://github.com/xenondevs/Nova/assets/88115382/be245208-5242-49d6-8469-308f83453ea6)

**Comment by NichtStudioCode** [comment]
> Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin. In order to do that, remove all other plugins from your server and check if the issue still persists. If the issue is caused by another plugin, select "This issue is about a specific plugin incompatibility" and state the name, version and where to download that plugin in your report.
