### ISSUE TITLE
Running a crash in Docker

### ISSUE THREAD

**Issue by postyizhan** [xenondevs/Nova#395]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova:0.16.1,paper:git-Paper-496(MC:1.20.4)

### Nova Addons and Versions

no addon

### Expected behavior

Nova in Docker runs normally like a host

### Observed/Actual behavior

The plugin encountered an error while loading and shut down the server

### Steps to reproduce

1. Download git-Paper-496 and successfully start
2. Install nova 0.16.1
3. Move to the Docker container and use 'azul/zulu openjdk: 21 jre latest' as the Java image
4. start server

### Server log

```
[03:45:00 INFO]: [Nova] Loading 2 libraries...
[03:45:00 INFO]: [Nova] Loaded library /Server/test/libraries/xyz/xenondevs/configurate/configurate-yaml/4.2.0-SNAPSHOT/configurate-yaml-4.2.0-SNAPSHOT.jar
[03:45:00 INFO]: [Nova] Loaded library /Server/test/libraries/xyz/xenondevs/configurate/configurate-core/4.2.0-SNAPSHOT/configurate-core-4.2.0-SNAPSHOT.jar
[03:45:00 INFO]: [Nova] Loaded library /Server/test/libraries/io/leangen/geantyref/geantyref/1.3.14/geantyref-1.3.14.jar
[03:45:00 INFO]: [Nova] Loaded library /Server/test/libraries/xyz/xenondevs/configurate/configurate-extra-kotlin/4.2.0-SNAPSHOT/configurate-extra-kotlin-4.2.0-SNAPSHOT.jar
[03:45:00 INFO]: [Nova] Loaded library /Server/test/libraries/org/jetbrains/kotlin/kotlin-stdlib-common/1.8.20/kotlin-stdlib-common-1.8.20.jar
[03:45:00 INFO]: [Nova] Loading server plugin Nova v0.16.1
[03:45:00 INFO]: Server permissions file permissions.yml is empty, ignoring it
[03:45:00 INFO]: [Nova] Enabling Nova v0.16.1
[03:45:01 INFO]: [Nova] Extracting default config
[03:45:02 INFO]: [Nova] Registering packet handlers
[03:45:02 INFO]: [Nova] Loading Addons...
[03:45:02 INFO]: [Nova] Applying patches...
[03:45:02 ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/transformer/Patcher
xyz.xenondevs.nova.transformer.PatcherException: 
    JDK: 21.0.3 by Azul Systems, Inc.
    JVM: OpenJDK 64-Bit Server VM, 21.0.3+9-LTS by Azul Systems, Inc.
    Operating system: Linux, amd64
    Startup parameters: []

        at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:86) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[?:?]
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[?:?]
        at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:75) ~[?:?]
        at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[?:?]
        at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[?:?]
        at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[?:?]
        at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process
        at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:701) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:631) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:611) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:563) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:540) ~[?:?]
        at xyz.xenondevs.bytebase.RuntimeUtilsKt$INSTRUMENTATION$2.invoke(RuntimeUtils.kt:13) ~[?:?]
        at xyz.xenondevs.bytebase.RuntimeUtilsKt$INSTRUMENTATION$2.invoke(RuntimeUtils.kt:13) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at xyz.xenondevs.bytebase.RuntimeUtilsKt.getINSTRUMENTATION(RuntimeUtils.kt:13) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.redefineModule(Patcher.kt:94) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:80) ~[?:?]
        ... 20 more
[03:45:02 WARN]: [Nova] Shutting down the server...
```

### Errors

```log
Please see Server log
```

**Comment by postyizhan** [comment]
> There's a similar problem: [byte-buddy/issues/374](https://github.com/raphw/byte-buddy/issues/374)
> 
> Could you try to use JDK instead of JRE?

solve the problem
