### ISSUE TITLE
[Bug] Chunks around Nova blocks not loading

### ISSUE THREAD

**Issue by SolarCiv** [xenondevs/Nova#40]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of Spigot or a Spigot fork.
- [X] I have checked for similar issues.

### Plugin Version and Server Software

Nova: v0.6, git-Paper-327 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8575248)

### Expected behavior

Being able to walk in chunks with Nova-related blocks/entities.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/91644728/137443213-97f82268-c556-4aa6-848a-39adb7cc5544.png)
![image](https://user-images.githubusercontent.com/91644728/137443224-21409f1d-3411-41d2-9306-780c9738d57a.png)
![image](https://user-images.githubusercontent.com/91644728/137443327-42682aca-b54b-4cfe-af3b-72ea601acbc2.png)

### Steps to reproduce

1. Load the server with the latest version of the Nova plugin.
2. Leave for a few hours with players setting up and using the plugins features.
3. Chunks are unloaded around Nova blocks, TPS drops, server crashes repeatedly.

### Errors

Unable to find any errors in console relating to Nova, however once the plugin was removed, and the server restarted, the chunks are okay again, and the server isn't crashing.

The only clue I could find was this in the timings report:
**Nova::Task: xyz.xenondevs.nova.util.SchedulerUtilsKt$$Lambda$10824 (interval:1)**
Using **92.61%** of the tick.

Removing the plugin fixed the issue:
![image](https://user-images.githubusercontent.com/91644728/137443585-373d7ee1-3761-4683-849f-965395f1cb75.png)

**Comment by ByteZ1337** [comment]
Please provide the full timings report

**Comment by XxMr1234GamerzxX** [comment]
`[11:52:30 ERROR]: Could not pass event ChunkUnloadEvent to Nova v0.6
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.save(net.minecraft.nbt.NBTTagCompound)" because "nmsStack" is null
        at xyz.xenondevs.nova.lib.de.studiocode.inventoryaccess.r7.util.ItemUtilsImpl.serializeItemStack(ItemUtilsImpl.java:39) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.lib.de.studiocode.inventoryaccess.r7.util.ItemUtilsImpl.serializeItemStack(ItemUtilsImpl.java:26) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.data.serialization.cbf.element.other.ItemStackElement.write(ItemStackElement.kt:14) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.data.serialization.cbf.element.CompoundElement.write(CompoundElement.kt:24) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.data.serialization.cbf.element.CompoundElement.write(CompoundElement.kt:24) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.data.serialization.cbf.element.CompoundElement.toByteArray(CompoundElement.kt:84) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.data.database.columtype.CompoundColumnType.valueToDB(CompoundColumnType.kt:19) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:12) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:52) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:135) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:121) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.lib.net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert(ExposedUpsertExtensions.kt:17) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.lib.net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert$default(ExposedUpsertExtensions.kt:11) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$saveChunk$1.invoke(TileEntityManager.kt:247) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$saveChunk$1.invoke(TileEntityManager.kt:243) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:179) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:205) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:213) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:204) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:156) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:213) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:126) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:123) ~[Nova-0.6.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:122) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager.saveChunk(TileEntityManager.kt:243) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager.handleChunkUnload(TileEntityManager.kt:230) ~[Nova-0.6.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager.handleChunkUnload(TileEntityManager.kt:286) ~[Nova-0.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor814.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-92]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-92]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-92]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.world.level.chunk.Chunk.unloadCallback(Chunk.java:1020) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$10(PlayerChunk.java:677) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:182) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.level.PlayerChunk.a(PlayerChunk.java:687) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.level.ChunkMapDistance.a(ChunkMapDistance.java:215) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.level.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:846) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:929) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:731) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Airplane-92]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-92]
        at java.lang.Thread.run(Thread.java:831) [?:?]`
        
        i have the chunk issue aswell with this in console

**Comment by NichtStudioCode** [comment]
@XxMr1234GamerzxX Please use Pastebin to post stack traces

**Comment by Sheikins** [comment]
I have the same problem on Paper 1.17.1

**Comment by Sheikins** [comment]
![image](https://user-images.githubusercontent.com/50546556/138007133-91597b96-a232-4e54-bb3d-5c35eac9bd64.png)

**Comment by NichtStudioCode** [comment]
Closing this as no one seems to encounter this issue anymore.
