### ISSUE TITLE
Nova incompatibility with plugins using the ClassGraph library

### ISSUE THREAD

**Issue by sgdc3** [xenondevs/Nova#417]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova: 0.16.2, Purpur: git-Purpur-2176 (MC: 1.20.4)

### Nova Addons and Versions

None

### Observed/Actual behavior

I'm unable to install Nova due to this error, it seems like your Java Agent doesn't like other plugins using the ClassGraph library.

### Steps to reproduce

Code to reproduce the issue:
```java
import io.github.classgraph.ClassGraph;
import org.bukkit.plugin.java.JavaPlugin;

public final class TestNova extends JavaPlugin {

    @Override
    public void onLoad() {
        new ClassGraph()
                .enableAllInfo()
                .acceptPackages(getClass().getPackage().getName())
                .scan();
    }
}
```

### Server log

```
[17:46:51] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[17:46:52] [ServerMain/INFO]: Loaded 1174 recipes
[17:46:52] [ServerMain/INFO]: Loaded 1271 advancements
[17:46:52] [Server thread/INFO]: Starting minecraft server version 1.20.4
[17:46:52] [Server thread/INFO]: Loading properties
[17:46:52] [Server thread/INFO]: This server is running Purpur version git-Purpur-2176 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 6b1ee98 on HEAD)
[17:46:53] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:46:53] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:46:53] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 7 worker threads, and gen parallelism of 7 threads
[17:46:53] [Server thread/WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[17:46:53] [Server thread/WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[17:46:53] [Server thread/WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[17:46:53] [Server thread/WARN]: [Pufferfish] Debug: Java: 21.0.4, test run: true
[17:46:53] [Server thread/INFO]: Default game type: SURVIVAL
[17:46:53] [Server thread/INFO]: Generating keypair
[17:46:53] [Server thread/INFO]: Starting Minecraft server on *:25565
[17:46:53] [Server thread/INFO]: Using default channel type
[17:46:53] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[17:46:53] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[17:46:53] [Server thread/INFO]: [Nova] Loading 2 libraries...
[17:46:53] [Server thread/INFO]: [Nova] Loaded library C:\Users\sgdc3\Desktop\NovaTest\libraries\xyz\xenondevs\configurate\configurate-yaml\4.2.0-SNAPSHOT\configurate-yaml-4.2.0-SNAPSHOT.jar
[17:46:53] [Server thread/INFO]: [Nova] Loaded library C:\Users\sgdc3\Desktop\NovaTest\libraries\xyz\xenondevs\configurate\configurate-core\4.2.0-SNAPSHOT\configurate-core-4.2.0-SNAPSHOT.jar
[17:46:53] [Server thread/INFO]: [Nova] Loaded library C:\Users\sgdc3\Desktop\NovaTest\libraries\io\leangen\geantyref\geantyref\1.3.14\geantyref-1.3.14.jar
[17:46:53] [Server thread/INFO]: [Nova] Loaded library C:\Users\sgdc3\Desktop\NovaTest\libraries\xyz\xenondevs\configurate\configurate-extra-kotlin\4.2.0-SNAPSHOT\configurate-extra-kotlin-4.2.0-SNAPSHOT.jar
[17:46:53] [Server thread/INFO]: [Nova] Loaded library C:\Users\sgdc3\Desktop\NovaTest\libraries\org\jetbrains\kotlin\kotlin-stdlib-common\1.8.20\kotlin-stdlib-common-1.8.20.jar
[17:46:53] [Server thread/INFO]: [spark] Loading server plugin spark v1.10.97
[17:46:53] [Server thread/INFO]: [TestNova] Loading server plugin TestNova v1.0.0-SNAPSHOT
[17:46:54] [Server thread/INFO]: [Nova] Loading server plugin Nova v0.16.2
[17:46:54] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:46:54] [Server thread/INFO]: [Nova] Enabling Nova v0.16.2
[17:46:54] [Server thread/INFO]: [Nova] Extracting default config
[17:46:55] [Server thread/INFO]: [Nova] Registering packet handlers
[17:46:55] [Server thread/INFO]: [Nova] Loading Addons...
[17:46:55] [Server thread/INFO]: [Nova] Applying patches...
[17:46:55] [Attach Listener/ERROR]: [STDERR] [sun.instrument.InstrumentationImpl] WARNING: A Java agent has been loaded dynamically (C:\Users\sgdc3\Desktop\NovaTest\libraries\net\bytebuddy\byte-buddy-agent\1.12.20\byte-buddy-agent-1.12.20.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
[17:46:57] [Server thread/ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/transformer/Patcher
xyz.xenondevs.nova.transformer.PatcherException: 
    JDK: 21.0.4 by Amazon.com Inc.
    JVM: OpenJDK 64-Bit Server VM, 21.0.4+7-LTS by Amazon.com Inc.
    Operating system: Windows 11, amd64
    Startup parameters: [-Xmx4G, -Xms4G]

	at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:86) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[?:?]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[?:?]
	at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:75) ~[?:?]
	at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[?:?]
	at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[?:?]
	at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[?:?]
	at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchFieldException: parent
	at java.lang.Class.getDeclaredField(Class.java:2782) ~[?:?]
	at xyz.xenondevs.nova.util.reflection.ReflectionUtils.getField(ReflectionUtils.kt:93) ~[?:?]
	at xyz.xenondevs.nova.util.reflection.ReflectionRegistry.CLASS_LOADER_PARENT_FIELD_delegate$lambda$0(ReflectionRegistry.kt:122) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at xyz.xenondevs.nova.util.reflection.ReflectionRegistry.getCLASS_LOADER_PARENT_FIELD(ReflectionRegistry.kt:122) ~[?:?]
	at xyz.xenondevs.nova.transformer.Patcher.insertPatchedLoader(Patcher.kt:178) ~[?:?]
	at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:83) ~[?:?]
	... 20 more
[17:46:57] [Server thread/WARN]: [Nova] Shutting down the server...
[17:46:57] [Server thread/ERROR]: Error occurred (in the plugin loader) while enabling Nova v0.16.2 (Is it up to date?)
java.lang.NoClassDefFoundError: xyz/xenondevs/nova/transformer/patch/misc/EventPreventionPatch
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:199) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: xyz.xenondevs.nova.transformer.patch.misc.EventPreventionPatch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 11 more
[17:46:57] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_20_R3.CraftServer] xyz/xenondevs/nova/transformer/patch/misc/EventPreventionPatch loading Nova v0.16.2 (Is it up to date?)
java.lang.NoClassDefFoundError: xyz/xenondevs/nova/transformer/patch/misc/EventPreventionPatch
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.handlePluginException(PaperPluginInstanceManager.java:312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:201) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: xyz.xenondevs.nova.transformer.patch.misc.EventPreventionPatch
	... 11 more
[17:46:57] [Server thread/INFO]: Preparing level "world"
[17:46:57] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: xyz/xenondevs/nova/transformer/patch/nbt/CBFCompoundTagPatch
	at net.minecraft.nbt.CompoundTag.a(CompoundTag.java) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.loadCompound(CompoundTag.java:57) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:42) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:35) ~[?:?]
	at net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:382) ~[?:?]
	at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:376) ~[?:?]
	at net.minecraft.nbt.NbtIo.read(NbtIo.java:306) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:73) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:39) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource.readLevelDataTagRaw(LevelStorageSource.java:287) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource.readLevelDataTagFixed(LevelStorageSource.java:291) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.getDataTag(LevelStorageSource.java:595) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.getDataTag(LevelStorageSource.java:586) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:529) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: xyz.xenondevs.nova.transformer.patch.nbt.CBFCompoundTagPatch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 19 more
[17:46:57] [Server thread/ERROR]: This crash report has been saved to: C:\Users\sgdc3\Desktop\NovaTest\.\crash-reports\crash-2024-08-14_17.46.57-server.txt
[17:46:57] [Server thread/INFO]: Stopping server
[17:46:57] [Server thread/INFO]: [Nova] Disabling Nova v0.16.2
[17:46:57] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling Nova v0.16.2 (Is it up to date?)
java.lang.NoClassDefFoundError: xyz/xenondevs/nova/transformer/patch/misc/EventPreventionPatch
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:221) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:147) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:584) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:986) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:862) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1298) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: xyz.xenondevs.nova.transformer.patch.misc.EventPreventionPatch
	... 12 more
[17:46:57] [Server thread/ERROR]: Exception stopping the server
java.lang.NoClassDefFoundError: xyz/xenondevs/nova/transformer/patch/misc/EventPreventionPatch
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.handlePluginException(PaperPluginInstanceManager.java:312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:241) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:147) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:584) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:986) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:862) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1298) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: xyz.xenondevs.nova.transformer.patch.misc.EventPreventionPatch
	... 12 more
```

### Errors

```log
[17:35:06 ERROR]: [Nova] An exception occurred trying to initialize xyz/xenondevs/nova/transformer/Patcher
xyz.xenondevs.nova.transformer.PatcherException:
    JDK: 21.0.4 by Amazon.com Inc.
    JVM: OpenJDK 64-Bit Server VM, 21.0.4+7-LTS by Amazon.com Inc.
    Operating system: Windows 11, amd64
    Startup parameters: [-Xmx4G, -Xms4G]

        at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:86) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[?:?]
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[?:?]
        at xyz.xenondevs.nova.initialize.InitializableClass.initialize(InitializableClass.kt:75) ~[?:?]
        at xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:136) ~[?:?]
        at xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:89) ~[?:?]
        at xyz.xenondevs.nova.Nova.onEnable(Nova.kt:74) ~[?:?]
        at xyz.xenondevs.nova.loader.NovaJavaPlugin.onEnable(NovaJavaPlugin.java:24) ~[Nova-0.16.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(Unknown Source) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchFieldException: parent
        at java.lang.Class.getDeclaredField(Class.java:2782) ~[?:?]
        at xyz.xenondevs.nova.util.reflection.ReflectionUtils.getField(ReflectionUtils.kt:93) ~[?:?]
        at xyz.xenondevs.nova.util.reflection.ReflectionRegistry.CLASS_LOADER_PARENT_FIELD_delegate$lambda$0(ReflectionRegistry.kt:122) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at xyz.xenondevs.nova.util.reflection.ReflectionRegistry.getCLASS_LOADER_PARENT_FIELD(ReflectionRegistry.kt:122) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.insertPatchedLoader(Patcher.kt:178) ~[?:?]
        at xyz.xenondevs.nova.transformer.Patcher.init(Patcher.kt:83) ~[?:?]
        ... 20 more
```

**Comment by NichtStudioCode** [comment]
Fixed with the switch to [origami](https://github.com/xenondevs/origami) in 0.21
