### ISSUE TITLE
Cant load the plugin on 1.20.6 purpur server...

### ISSUE THREAD

**Issue by rayman202** [xenondevs/Nova#428]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.17-alpha.9, purpur 2233

### Nova Addons and Versions

Im not using addons

### Observed/Actual behavior

I cant load the plugin, idk why

### Steps to reproduce

Cant load the plugin in purpur 1.20.6

### Server log

[22:26:19] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[22:26:19] [ServerMain/INFO]: Loaded 1175 recipes
[22:26:19] [ServerMain/INFO]: Loaded 1276 advancements
[22:26:20] [Server thread/INFO]: Starting minecraft server version 1.20.6
[22:26:20] [Server thread/WARN]: ****************************
[22:26:20] [Server thread/WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[22:26:20] [Server thread/WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[22:26:20] [Server thread/WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[22:26:20] [Server thread/WARN]: ****************************
[22:26:20] [Server thread/INFO]: Loading properties
[22:26:20] [Server thread/INFO]: This server is running Purpur version 1.20.6-2233-ver/1.20.6@0d6766e (2024-06-18T04:01:10Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[22:26:21] [Server thread/INFO]: Server Ping Player Sample Count: 12
[22:26:21] [Server thread/INFO]: Using 4 threads for Netty based IO
[22:26:21] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[22:26:21] [Server thread/INFO]: Default game type: SURVIVAL
[22:26:21] [Server thread/INFO]: Generating keypair
[22:26:21] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:26:21] [Server thread/INFO]: Using default channel type
[22:26:21] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[22:26:21] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[22:26:21] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'Nova-0.17-alpha.9.jar' in folder 'plugins'
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:60) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:29) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:169) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:139) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.resources.ResourceLocation net.minecraft.resources.ResourceLocation.fromNamespaceAndPath(java.lang.String, java.lang.String)'
	at Nova-0.17-alpha.9.jar/xyz.xenondevs.nova.registry.NovaRegistries.simpleRegistry(NovaRegistries.kt:71) ~[Nova-0.17-alpha.9.jar:?]
	at Nova-0.17-alpha.9.jar/xyz.xenondevs.nova.registry.NovaRegistries.<clinit>(NovaRegistries.kt:26) ~[Nova-0.17-alpha.9.jar:?]
	at Nova-0.17-alpha.9.jar/xyz.xenondevs.nova.serialization.json.GsonKt.<clinit>(Gson.kt:54) ~[Nova-0.17-alpha.9.jar:?]
	at Nova-0.17-alpha.9.jar/xyz.xenondevs.nova.Nova.<init>(Nova.kt:124) ~[Nova-0.17-alpha.9.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	... 14 more
[22:26:21] [Server thread/INFO]: [spark] Loading server plugin spark v1.10.97
[22:26:21] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:26:21] [Server thread/INFO]: Preparing level "world"
[22:26:22] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:26:22] [Server thread/INFO]: Time elapsed: 556 ms
[22:26:22] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[22:26:22] [Server thread/INFO]: Time elapsed: 62 ms
[22:26:22] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[22:26:22] [Server thread/INFO]: Time elapsed: 47 ms
[22:26:22] [Server thread/INFO]: [spark] Enabling spark v1.10.97
[22:26:23] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[22:26:23] [Server thread/INFO]: [spark] Starting background profiler...
[22:26:23] [Server thread/INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
[22:26:23] [Server thread/INFO]: Running delayed init tasks
[22:26:23] [Server thread/INFO]: Done (3.054s)! For help, type "help"

### Errors

```log
I want to use Nova for my server but the plugin doesnt load, I tried to look what the problem is but I cant find anything :(
```

### Additional context

Originally I was using a server with other plugins as Itemsadder and modelengine and more, I tought that the problem were other plugins so I started to remove all the plugins and I only let Nova but it  still cant load the plugin properly.

**Comment by NichtStudioCode** [comment]
Nova v0.17 is not compatible with 1.20.6
