### ISSUE TITLE
Conflict between Nova and OriginsPaper

### ISSUE THREAD

**Issue by gabriel-fresan** [xenondevs/Nova#445]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova 0.17-alpha.14, Purpur 1.21.1-2294-1d3cef7 (MC: 1.21.1)*

### Nova Addons and Versions

Logistics V0.2.9-alpha.2, Machines 0.4.6-alpha.6, Simple Upgrades 1.4-alpha.1

### Expected behavior

Normal server start

### Observed/Actual behavior

On starting the server with both [OriginsPaper](https://github.com/Dueris/OriginsPaper) and Nova the server does not start with Nova Returning an error

### Steps to reproduce

install any version of Nova and PaperOrigins 1.2.0 or higher

### Server log

[latest.log on github](https://github.com/user-attachments/files/16881527/latest.log)
[latest.log on mclo.gs](https://mclo.gs/KYwEWDF)

### Errors

```log
[19:04:02 ERROR]: [STDERR] [sun.instrument.InstrumentationImpl] WARNING: A Java agent has been loaded dynamically (C:\Users\gabri\AppData\Local\Temp\byteBuddyAgent17443203460006122800.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
[19:04:07 ERROR]: [Nova] An exception occurred during initialization
xyz.xenondevs.nova.patch.PatcherException:
    JDK: 21.0.4 by Eclipse Adoptium
    JVM: OpenJDK 64-Bit Server VM, 21.0.4+7-LTS by Eclipse Adoptium
    Operating system: Windows 11, amd64
    Startup parameters: [-Xms8192M, -Xmx12288M, -XX:+AlwaysPreTouch, -XX:+DisableExplicitGC, -XX:+ParallelRefProcEnabled, -XX:+PerfDisableSharedMem, -XX:+UnlockExperimentalVMOptions, -XX:+UseG1GC, -XX:G1HeapRegionSize=8M, -XX:G1HeapWastePercent=5, -XX:G1MaxNewSizePercent=40, -XX:G1MixedGCCountTarget=4, -XX:G1MixedGCLiveThresholdPercent=90, -XX:G1NewSizePercent=30, -XX:G1RSetUpdatingPauseTimePercent=5, -XX:G1ReservePercent=20, -XX:InitiatingHeapOccupancyPercent=15, -XX:MaxGCPauseMillis=200, -XX:MaxTenuringThreshold=1, -XX:SurvivorRatio=32, -Dusing.aikars.flags=https://mcflags.emc.gs, -Daikars.new.flags=true]

        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.patch.Patcher.init(Patcher.kt:87) ~[Nova-0.17-alpha.14.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[?:?]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[?:?]
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[?:?]
        at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:54) ~[?:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.initialize.InitializableFunction.run(Initializable.kt:157) ~[Nova-0.17-alpha.14.jar:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.initialize.Initializer$launch$1$1.invokeSuspend(Initializer.kt:270) ~[Nova-0.17-alpha.14.jar:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.initialize.Initializer$launch$1$1.invoke(Initializer.kt) ~[Nova-0.17-alpha.14.jar:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.initialize.Initializer$launch$1$1.invoke(Initializer.kt) ~[Nova-0.17-alpha.14.jar:?]
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61) ~[?:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163) ~[?:?]
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source) ~[?:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.initialize.Initializer$launch$1.invokeSuspend(Initializer.kt:266) ~[Nova-0.17-alpha.14.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[?:?]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277) ~[?:?]
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) ~[?:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) ~[?:?]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[?:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48) ~[?:?]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[?:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:187) ~[Nova-0.17-alpha.14.jar:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:66) ~[Nova-0.17-alpha.14.jar:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.Nova.onEnable(Nova.kt:67) ~[Nova-0.17-alpha.14.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(Unknown Source) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(Unknown Source) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(Unknown Source) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:330) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchFieldException: parent
        at java.base/java.lang.Class.getDeclaredField(Class.java:2782) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[purpur-1.21.1.jar:1.21.1-2294-1d3cef7]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.util.reflection.ReflectionUtils.getField(ReflectionUtils.kt:122) ~[Nova-0.17-alpha.14.jar:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.util.reflection.ReflectionRegistry.CLASS_LOADER_PARENT_FIELD_delegate$lambda$0(ReflectionRegistry.kt:79) ~[Nova-0.17-alpha.14.jar:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.util.reflection.ReflectionRegistry.getCLASS_LOADER_PARENT_FIELD(ReflectionRegistry.kt:79) ~[Nova-0.17-alpha.14.jar:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.patch.Patcher.insertPatchedLoader(Patcher.kt:179) ~[Nova-0.17-alpha.14.jar:?]
        at Nova-0.17-alpha.14.jar/xyz.xenondevs.nova.patch.Patcher.init(Patcher.kt:84) ~[Nova-0.17-alpha.14.jar:?]
        ... 35 more
[19:04:07 ERROR]: [Nova] Initialization failure
```

**Comment by Dueris** [comment]
Hey! I am the developer of OriginsPaper, and this issue was brought to my attention a little bit ago. I believe its a conflict with our "patchers" for the source, OriginsPaper has an implementation of MIXIN using java agents and bytecode libraries. If you need me to resolve anything on my end LMK, Im happy to help out whenever to fix this compat issue

**Comment by VulcanoSoftware** [comment]
Is this fixed right now?

**Comment by NichtStudioCode** [comment]
Closing this as the OriginsPaper seems to be abandoned
