### ISSUE TITLE
[Bug] Nova doesn't respect advancements being disabled by Spigot

### ISSUE THREAD

**Issue by ArtelGG** [xenondevs/Nova#66]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This bug also occurs when no other plugins are present.

### Plugin Version, Server Software, Server Version

Nova: 0.7.2, Spigot: 3383-Spigot-8965a50-b8a25cb (MC: 1.18.1)

### Expected behavior

The plugin should properly recognize that advancements are not enabled on the server and subsequently not attempt to add any.

### Observed/Actual behavior

The console will receive a NPE stack trace every time a player joins the server. From what I can tell from limited testing it doesn't appear to break any functionality of the plugin itself.

### Steps to reproduce

Modify the `spigot.yml` configuration file in the main directory of the server and add/modify the following configuration options to it:
```
advancements:
  disable-saving: true
  disabled:
  - '*'
```
Then start the server up and join.

### Errors

```
[Server thread/ERROR]: Could not pass event PlayerJoinEvent to Nova v0.7.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:277) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:193) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.network.LoginListener.b(LoginListener.java:74) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1322) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3383-Spigot-8965a50-b8a25cb]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException
        at xyz.xenondevs.nova.util.EntityUtilsKt.awardAdvancement(EntityUtils.kt:37) ~[?:?]
        at xyz.xenondevs.nova.player.advancement.AdvancementManager.handlePlayerJoin(AdvancementManager.kt:122) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 15 more
```

### Additional context

This is a very common way for servers to disable the spam of achievement announcements without having to go through the hassle of manually assigning the gamerule (`/gamerule announceAdvancements false`) to every single world present on the server.

**Comment by NichtStudioCode** [comment]
Thanks for reporting! This will be fixed in the next patch.
